package f.g.e;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/* loaded from: classes2.dex */
public final class e {

    private static final Map<String, String> a;
    private static final Map<String, String> b;
    static {
        HashMap hashMap = new HashMap();
        e.a = hashMap;
        HashMap hashMap2 = new HashMap();
        e.b = hashMap2;
        e.a("application/andrew-inset", "ez");
        e.a("application/dsptype", "tsp");
        e.a("application/epub+zip", "epub");
        e.a("application/hta", "hta");
        e.a("application/mac-binhex40", "hqx");
        e.a("application/mathematica", "nb");
        e.a("application/msaccess", "mdb");
        e.a("application/oda", "oda");
        e.a("application/ogg", "ogx");
        e.a("application/pdf", "pdf");
        e.a("application/pgp-keys", "key");
        e.a("application/pgp-signature", "pgp");
        e.a("application/pics-rules", "prf");
        e.a("application/pkix-cert", "cer");
        e.a("application/rar", "rar");
        e.a("application/rdf+xml", "rdf");
        e.a("application/rss+xml", "rss");
        e.a("application/zip", "zip");
        e.a("application/vnd.android.package-archive", "apk");
        e.a("application/vnd.cinderella", "cdy");
        e.a("application/vnd.ms-pki.stl", "stl");
        e.a("application/vnd.oasis.opendocument.database", "odb");
        e.a("application/vnd.oasis.opendocument.formula", "odf");
        e.a("application/vnd.oasis.opendocument.graphics", "odg");
        e.a("application/vnd.oasis.opendocument.graphics-template", "otg");
        e.a("application/vnd.oasis.opendocument.image", "odi");
        e.a("application/vnd.oasis.opendocument.presentation", "odp");
        e.a("application/vnd.oasis.opendocument.presentation-template", "otp");
        e.a("application/vnd.oasis.opendocument.spreadsheet", "ods");
        e.a("application/vnd.oasis.opendocument.spreadsheet-template", "ots");
        e.a("application/vnd.oasis.opendocument.text", "odt");
        e.a("application/vnd.oasis.opendocument.text-master", "odm");
        e.a("application/vnd.oasis.opendocument.text-template", "ott");
        e.a("application/vnd.oasis.opendocument.text-web", "oth");
        e.a("application/vnd.google-earth.kml+xml", "kml");
        e.a("application/vnd.google-earth.kmz", "kmz");
        String str37 = "application/msword";
        e.a(str37, "doc");
        e.a(str37, "dot");
        e.a("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx");
        e.a("application/vnd.openxmlformats-officedocument.wordprocessingml.template", "dotx");
        String str40 = "application/vnd.ms-excel";
        e.a(str40, "xls");
        e.a(str40, "xlt");
        e.a("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx");
        e.a("application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xltx");
        String str43 = "application/vnd.ms-powerpoint";
        e.a(str43, "ppt");
        e.a(str43, "pot");
        e.a(str43, "pps");
        e.a("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx");
        e.a("application/vnd.openxmlformats-officedocument.presentationml.template", "potx");
        e.a("application/vnd.openxmlformats-officedocument.presentationml.slideshow", "ppsx");
        e.a("application/vnd.rim.cod", "cod");
        e.a("application/vnd.smaf", "mmf");
        e.a("application/vnd.stardivision.calc", "sdc");
        e.a("application/vnd.stardivision.draw", "sda");
        String str51 = "application/vnd.stardivision.impress";
        e.a(str51, "sdd");
        e.a(str51, "sdp");
        e.a("application/vnd.stardivision.math", "smf");
        e.a("application/vnd.stardivision.writer", "sdw");
        e.a("application/vnd.stardivision.writer", "vor");
        e.a("application/vnd.stardivision.writer-global", "sgl");
        e.a("application/vnd.sun.xml.calc", "sxc");
        e.a("application/vnd.sun.xml.calc.template", "stc");
        e.a("application/vnd.sun.xml.draw", "sxd");
        e.a("application/vnd.sun.xml.draw.template", "std");
        e.a("application/vnd.sun.xml.impress", "sxi");
        e.a("application/vnd.sun.xml.impress.template", "sti");
        e.a("application/vnd.sun.xml.math", "sxm");
        e.a("application/vnd.sun.xml.writer", "sxw");
        e.a("application/vnd.sun.xml.writer.global", "sxg");
        e.a("application/vnd.sun.xml.writer.template", "stw");
        e.a("application/vnd.visio", "vsd");
        e.a("application/x-abiword", "abw");
        e.a("application/x-apple-diskimage", "dmg");
        e.a("application/x-bcpio", "bcpio");
        e.a("application/x-bittorrent", "torrent");
        e.a("application/x-cdf", "cdf");
        e.a("application/x-cdlink", "vcd");
        e.a("application/x-chess-pgn", "pgn");
        e.a("application/x-cpio", "cpio");
        e.a("application/x-debian-package", "deb");
        e.a("application/x-debian-package", "udeb");
        String str77 = "application/x-director";
        e.a(str77, "dcr");
        e.a(str77, "dir");
        e.a(str77, "dxr");
        e.a("application/x-dms", "dms");
        e.a("application/x-doom", "wad");
        e.a("application/x-dvi", "dvi");
        String str81 = "application/x-font";
        e.a(str81, "pfa");
        e.a(str81, "pfb");
        e.a(str81, "gsf");
        e.a(str81, "pcf");
        e.a(str81, "pcf.Z");
        e.a("application/x-freemind", "mm");
        e.a("application/x-futuresplash", "spl");
        e.a("application/futuresplash", "spl");
        e.a("application/x-gnumeric", "gnumeric");
        e.a("application/x-go-sgf", "sgf");
        e.a("application/x-graphing-calculator", "gcf");
        String str88 = "application/x-gtar";
        e.a(str88, "tgz");
        e.a(str88, "gtar");
        e.a(str88, "taz");
        e.a("application/x-hdf", "hdf");
        e.a("application/x-hwp", "hwp");
        e.a("application/x-ica", "ica");
        e.a("application/x-internet-signup", "ins");
        e.a("application/x-internet-signup", "isp");
        e.a("application/x-iphone", "iii");
        e.a("application/x-iso9660-image", "iso");
        e.a("application/x-jmol", "jmz");
        e.a("application/x-kchart", "chrt");
        e.a("application/x-killustrator", "kil");
        String str99 = "application/x-koan";
        e.a(str99, "skp");
        e.a(str99, "skd");
        e.a(str99, "skt");
        e.a(str99, "skm");
        e.a("application/x-kpresenter", "kpr");
        e.a("application/x-kpresenter", "kpt");
        e.a("application/x-kspread", "ksp");
        e.a("application/x-kword", "kwd");
        e.a("application/x-kword", "kwt");
        e.a("application/x-latex", "latex");
        e.a("application/x-lha", "lha");
        e.a("application/x-lzh", "lzh");
        e.a("application/x-lzx", "lzx");
        String str109 = "application/x-maker";
        e.a(str109, "frm");
        e.a(str109, "maker");
        e.a(str109, "frame");
        e.a(str109, "fb");
        e.a(str109, "book");
        e.a(str109, "fbdoc");
        e.a("application/x-mif", "mif");
        e.a("application/x-ms-wmd", "wmd");
        e.a("application/x-ms-wmz", "wmz");
        e.a("application/x-msi", "msi");
        e.a("application/x-ns-proxy-autoconfig", "pac");
        e.a("application/x-nwc", "nwc");
        e.a("application/x-object", "o");
        e.a("application/x-oz-application", "oza");
        e.a("application/x-pem-file", "pem");
        e.a("application/x-pkcs12", "p12");
        e.a("application/x-pkcs12", "pfx");
        e.a("application/x-pkcs7-certreqresp", "p7r");
        e.a("application/x-pkcs7-crl", "crl");
        e.a("application/x-quicktimeplayer", "qtl");
        e.a("application/x-shar", "shar");
        e.a("application/x-shockwave-flash", "swf");
        e.a("application/x-stuffit", "sit");
        e.a("application/x-sv4cpio", "sv4cpio");
        e.a("application/x-sv4crc", "sv4crc");
        e.a("application/x-tar", "tar");
        e.a("application/x-texinfo", "texinfo");
        e.a("application/x-texinfo", "texi");
        e.a("application/x-troff", "t");
        e.a("application/x-troff", "roff");
        e.a("application/x-troff-man", "man");
        e.a("application/x-ustar", "ustar");
        e.a("application/x-wais-source", "src");
        e.a("application/x-wingz", "wz");
        e.a("application/x-webarchive", "webarchive");
        e.a("application/x-webarchive-xml", "webarchivexml");
        String str446 = "crt";
        e.a("application/x-x509-ca-cert", str446);
        e.a("application/x-x509-user-cert", str446);
        e.a("application/x-x509-server-cert", str446);
        e.a("application/x-xcf", "xcf");
        e.a("application/x-xfig", "fig");
        e.a("application/xhtml+xml", "xhtml");
        e.a("video/3gpp", "3gpp");
        e.a("video/3gpp", "3gp");
        e.a("video/3gpp2", "3gpp2");
        e.a("video/3gpp2", "3g2");
        e.a("audio/3gpp", "3gpp");
        e.a("audio/aac", "aac");
        e.a("audio/aac-adts", "aac");
        e.a("audio/amr", "amr");
        e.a("audio/amr-wb", "awb");
        e.a("audio/basic", "snd");
        e.a("audio/flac", "flac");
        e.a("application/x-flac", "flac");
        e.a("audio/imelody", "imy");
        String str159 = "audio/midi";
        e.a(str159, "mid");
        e.a(str159, "midi");
        e.a(str159, "ota");
        e.a(str159, "kar");
        e.a(str159, "rtttl");
        e.a(str159, "xmf");
        e.a("audio/mobile-xmf", "mxmf");
        String str161 = "audio/mpeg";
        e.a(str161, "mp3");
        e.a(str161, "mpga");
        e.a(str161, "mpega");
        e.a(str161, "mp2");
        e.a(str161, "m4a");
        e.a("audio/mpegurl", "m3u");
        String str163 = "audio/ogg";
        e.a(str163, "oga");
        e.a(str163, "ogg");
        e.a(str163, "spx");
        e.a("audio/prs.sid", "sid");
        String str165 = "audio/x-aiff";
        e.a(str165, "aif");
        e.a(str165, "aiff");
        e.a(str165, "aifc");
        e.a("audio/x-gsm", "gsm");
        e.a("audio/x-matroska", "mka");
        e.a("audio/x-mpegurl", "m3u");
        e.a("audio/x-ms-wma", "wma");
        e.a("audio/x-ms-wax", "wax");
        String str171 = "audio/x-pn-realaudio";
        e.a(str171, "ra");
        e.a(str171, "rm");
        e.a(str171, "ram");
        e.a("audio/x-realaudio", "ra");
        e.a("audio/x-scpls", "pls");
        e.a("audio/x-sd2", "sd2");
        e.a("audio/x-wav", "wav");
        e.a("image/x-ms-bmp", "bmp");
        e.a("image/bmp", "bmp");
        e.a("image/gif", "gif");
        e.a("image/x-icon", "ico");
        e.a("image/ico", "cur");
        e.a("image/ico", "ico");
        e.a("image/ief", "ief");
        String str183 = "image/jpeg";
        e.a(str183, "jpg");
        e.a(str183, "jpeg");
        e.a(str183, "jpe");
        e.a("image/pcx", "pcx");
        e.a("image/png", "png");
        e.a("image/svg+xml", "svg");
        e.a("image/svg+xml", "svgz");
        e.a("image/tiff", "tiff");
        e.a("image/tiff", "tif");
        e.a("image/vnd.djvu", "djvu");
        e.a("image/vnd.djvu", "djv");
        e.a("image/vnd.wap.wbmp", "wbmp");
        e.a("image/webp", "webp");
        e.a("image/x-adobe-dng", "dng");
        e.a("image/x-canon-cr2", "cr2");
        e.a("image/x-cmu-raster", "ras");
        e.a("image/x-coreldraw", "cdr");
        e.a("image/x-coreldrawpattern", "pat");
        e.a("image/x-coreldrawtemplate", "cdt");
        e.a("image/x-corelphotopaint", "cpt");
        e.a("image/x-fuji-raf", "raf");
        e.a("image/x-jg", "art");
        e.a("image/x-jng", "jng");
        e.a("image/x-nikon-nef", "nef");
        e.a("image/x-nikon-nrw", "nrw");
        e.a("image/x-olympus-orf", "orf");
        e.a("image/x-panasonic-rw2", "rw2");
        e.a("image/x-pentax-pef", "pef");
        e.a("image/x-photoshop", "psd");
        e.a("image/x-portable-anymap", "pnm");
        e.a("image/x-portable-bitmap", "pbm");
        e.a("image/x-portable-graymap", "pgm");
        e.a("image/x-portable-pixmap", "ppm");
        e.a("image/x-samsung-srw", "srw");
        e.a("image/x-sony-arw", "arw");
        e.a("image/x-rgb", "rgb");
        e.a("image/x-xbitmap", "xbm");
        e.a("image/x-xpixmap", "xpm");
        e.a("image/x-xwindowdump", "xwd");
        e.a("model/iges", "igs");
        e.a("model/iges", "iges");
        String str222 = "model/mesh";
        e.a(str222, "msh");
        e.a(str222, "mesh");
        e.a(str222, "silo");
        e.a("text/calendar", "ics");
        e.a("text/calendar", "icz");
        e.a("text/comma-separated-values", "csv");
        e.a("text/css", "css");
        e.a("text/html", "htm");
        e.a("text/html", "html");
        e.a("text/h323", "323");
        e.a("text/iuls", "uls");
        e.a("text/mathml", "mml");
        String str232 = "text/plain";
        e.a(str232, "txt");
        e.a(str232, "asc");
        e.a(str232, "text");
        e.a(str232, "diff");
        e.a(str232, "po");
        e.a("text/richtext", "rtx");
        e.a("text/rtf", "rtf");
        e.a("text/text", "phps");
        e.a("text/tab-separated-values", "tsv");
        e.a("text/xml", "xml");
        e.a("text/x-bibtex", "bib");
        e.a("text/x-boo", "boo");
        String str240 = "text/x-c++hdr";
        e.a(str240, "hpp");
        e.a(str240, "h++");
        e.a(str240, "hxx");
        e.a(str240, "hh");
        String str241 = "text/x-c++src";
        e.a(str241, "cpp");
        e.a(str241, "c++");
        e.a(str241, "cc");
        e.a(str241, "cxx");
        e.a("text/x-chdr", "h");
        e.a("text/x-component", "htc");
        e.a("text/x-csh", "csh");
        e.a("text/x-csrc", "c");
        e.a("text/x-dsrc", "d");
        e.a("text/x-haskell", "hs");
        e.a("text/x-java", "java");
        e.a("text/x-literate-haskell", "lhs");
        e.a("text/x-moc", "moc");
        e.a("text/x-pascal", "p");
        e.a("text/x-pascal", "pas");
        e.a("text/x-pcs-gcd", "gcd");
        e.a("text/x-setext", "etx");
        e.a("text/x-tcl", "tcl");
        String str256 = "text/x-tex";
        e.a(str256, "tex");
        e.a(str256, "ltx");
        e.a(str256, "sty");
        e.a(str256, "cls");
        e.a("text/x-vcalendar", "vcs");
        e.a("text/x-vcard", "vcf");
        e.a("video/avi", "avi");
        e.a("video/dl", "dl");
        e.a("video/dv", "dif");
        e.a("video/dv", "dv");
        e.a("video/fli", "fli");
        e.a("video/m4v", "m4v");
        e.a("video/mp2ts", "ts");
        String str266 = "video/mpeg";
        e.a(str266, "mpeg");
        e.a(str266, "mpg");
        e.a(str266, "mpe");
        e.a("video/mp4", "mp4");
        e.a(str266, "VOB");
        e.a("video/ogg", "ogv");
        e.a("video/quicktime", "qt");
        e.a("video/quicktime", "mov");
        e.a("video/vnd.mpegurl", "mxu");
        e.a("video/webm", "webm");
        e.a("video/x-la-asf", "lsf");
        e.a("video/x-la-asf", "lsx");
        e.a("video/x-matroska", "mkv");
        e.a("video/x-mng", "mng");
        e.a("video/x-ms-asf", "asf");
        e.a("video/x-ms-asf", "asx");
        e.a("video/x-ms-wm", "wm");
        e.a("video/x-ms-wmv", "wmv");
        e.a("video/x-ms-wmx", "wmx");
        e.a("video/x-ms-wvx", "wvx");
        e.a("video/x-sgi-movie", "movie");
        e.a("video/x-webex", "wrf");
        e.a("x-conference/x-cooltalk", "ice");
        e.a("x-epoc/x-sisx-app", "sisx");
    }

    private static void a(String string, String string2) {
        Map map = e.a;
        if (!map.containsKey(string)) {
            map.put(string, string2);
        }
        Map map2 = e.b;
        if (!map2.containsKey(string2)) {
            map2.put(string2, string);
        }
    }

    public static String b(String string) {
        boolean empty;
        if (string != null && string.isEmpty()) {
            if (string.isEmpty()) {
            }
            return (String)e.b.get(string.toLowerCase(Locale.US));
        }
        return null;
    }
}
