//! Dalvik opcodes

use crate::insns::InsnFormat;

/// Dalvik opcode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Opcode {
    Nop = 0x00,
    Move = 0x01,
    MoveFrom16 = 0x02,
    Move16 = 0x03,
    MoveWide = 0x04,
    MoveWideFrom16 = 0x05,
    MoveWide16 = 0x06,
    MoveObject = 0x07,
    MoveObjectFrom16 = 0x08,
    MoveObject16 = 0x09,
    MoveResult = 0x0a,
    MoveResultWide = 0x0b,
    MoveResultObject = 0x0c,
    MoveException = 0x0d,
    ReturnVoid = 0x0e,
    Return = 0x0f,
    ReturnWide = 0x10,
    ReturnObject = 0x11,
    Const4 = 0x12,
    Const16 = 0x13,
    Const = 0x14,
    ConstHigh16 = 0x15,
    ConstWide16 = 0x16,
    ConstWide32 = 0x17,
    ConstWide = 0x18,
    ConstWideHigh16 = 0x19,
    ConstString = 0x1a,
    ConstStringJumbo = 0x1b,
    ConstClass = 0x1c,
    MonitorEnter = 0x1d,
    MonitorExit = 0x1e,
    CheckCast = 0x1f,
    InstanceOf = 0x20,
    ArrayLength = 0x21,
    NewInstance = 0x22,
    NewArray = 0x23,
    FilledNewArray = 0x24,
    FilledNewArrayRange = 0x25,
    FillArrayData = 0x26,
    Throw = 0x27,
    Goto = 0x28,
    Goto16 = 0x29,
    Goto32 = 0x2a,
    PackedSwitch = 0x2b,
    SparseSwitch = 0x2c,
    CmplFloat = 0x2d,
    CmpgFloat = 0x2e,
    CmplDouble = 0x2f,
    CmpgDouble = 0x30,
    CmpLong = 0x31,
    IfEq = 0x32,
    IfNe = 0x33,
    IfLt = 0x34,
    IfGe = 0x35,
    IfGt = 0x36,
    IfLe = 0x37,
    IfEqz = 0x38,
    IfNez = 0x39,
    IfLtz = 0x3a,
    IfGez = 0x3b,
    IfGtz = 0x3c,
    IfLez = 0x3d,
    // 0x3e-0x43 unused
    Aget = 0x44,
    AgetWide = 0x45,
    AgetObject = 0x46,
    AgetBoolean = 0x47,
    AgetByte = 0x48,
    AgetChar = 0x49,
    AgetShort = 0x4a,
    Aput = 0x4b,
    AputWide = 0x4c,
    AputObject = 0x4d,
    AputBoolean = 0x4e,
    AputByte = 0x4f,
    AputChar = 0x50,
    AputShort = 0x51,
    Iget = 0x52,
    IgetWide = 0x53,
    IgetObject = 0x54,
    IgetBoolean = 0x55,
    IgetByte = 0x56,
    IgetChar = 0x57,
    IgetShort = 0x58,
    Iput = 0x59,
    IputWide = 0x5a,
    IputObject = 0x5b,
    IputBoolean = 0x5c,
    IputByte = 0x5d,
    IputChar = 0x5e,
    IputShort = 0x5f,
    Sget = 0x60,
    SgetWide = 0x61,
    SgetObject = 0x62,
    SgetBoolean = 0x63,
    SgetByte = 0x64,
    SgetChar = 0x65,
    SgetShort = 0x66,
    Sput = 0x67,
    SputWide = 0x68,
    SputObject = 0x69,
    SputBoolean = 0x6a,
    SputByte = 0x6b,
    SputChar = 0x6c,
    SputShort = 0x6d,
    InvokeVirtual = 0x6e,
    InvokeSuper = 0x6f,
    InvokeDirect = 0x70,
    InvokeStatic = 0x71,
    InvokeInterface = 0x72,
    // 0x73 unused
    InvokeVirtualRange = 0x74,
    InvokeSuperRange = 0x75,
    InvokeDirectRange = 0x76,
    InvokeStaticRange = 0x77,
    InvokeInterfaceRange = 0x78,
    // 0x79-0x7a unused
    NegInt = 0x7b,
    NotInt = 0x7c,
    NegLong = 0x7d,
    NotLong = 0x7e,
    NegFloat = 0x7f,
    NegDouble = 0x80,
    IntToLong = 0x81,
    IntToFloat = 0x82,
    IntToDouble = 0x83,
    LongToInt = 0x84,
    LongToFloat = 0x85,
    LongToDouble = 0x86,
    FloatToInt = 0x87,
    FloatToLong = 0x88,
    FloatToDouble = 0x89,
    DoubleToInt = 0x8a,
    DoubleToLong = 0x8b,
    DoubleToFloat = 0x8c,
    IntToByte = 0x8d,
    IntToChar = 0x8e,
    IntToShort = 0x8f,
    AddInt = 0x90,
    SubInt = 0x91,
    MulInt = 0x92,
    DivInt = 0x93,
    RemInt = 0x94,
    AndInt = 0x95,
    OrInt = 0x96,
    XorInt = 0x97,
    ShlInt = 0x98,
    ShrInt = 0x99,
    UshrInt = 0x9a,
    AddLong = 0x9b,
    SubLong = 0x9c,
    MulLong = 0x9d,
    DivLong = 0x9e,
    RemLong = 0x9f,
    AndLong = 0xa0,
    OrLong = 0xa1,
    XorLong = 0xa2,
    ShlLong = 0xa3,
    ShrLong = 0xa4,
    UshrLong = 0xa5,
    AddFloat = 0xa6,
    SubFloat = 0xa7,
    MulFloat = 0xa8,
    DivFloat = 0xa9,
    RemFloat = 0xaa,
    AddDouble = 0xab,
    SubDouble = 0xac,
    MulDouble = 0xad,
    DivDouble = 0xae,
    RemDouble = 0xaf,
    AddInt2Addr = 0xb0,
    SubInt2Addr = 0xb1,
    MulInt2Addr = 0xb2,
    DivInt2Addr = 0xb3,
    RemInt2Addr = 0xb4,
    AndInt2Addr = 0xb5,
    OrInt2Addr = 0xb6,
    XorInt2Addr = 0xb7,
    ShlInt2Addr = 0xb8,
    ShrInt2Addr = 0xb9,
    UshrInt2Addr = 0xba,
    AddLong2Addr = 0xbb,
    SubLong2Addr = 0xbc,
    MulLong2Addr = 0xbd,
    DivLong2Addr = 0xbe,
    RemLong2Addr = 0xbf,
    AndLong2Addr = 0xc0,
    OrLong2Addr = 0xc1,
    XorLong2Addr = 0xc2,
    ShlLong2Addr = 0xc3,
    ShrLong2Addr = 0xc4,
    UshrLong2Addr = 0xc5,
    AddFloat2Addr = 0xc6,
    SubFloat2Addr = 0xc7,
    MulFloat2Addr = 0xc8,
    DivFloat2Addr = 0xc9,
    RemFloat2Addr = 0xca,
    AddDouble2Addr = 0xcb,
    SubDouble2Addr = 0xcc,
    MulDouble2Addr = 0xcd,
    DivDouble2Addr = 0xce,
    RemDouble2Addr = 0xcf,
    AddIntLit16 = 0xd0,
    RsubInt = 0xd1,
    MulIntLit16 = 0xd2,
    DivIntLit16 = 0xd3,
    RemIntLit16 = 0xd4,
    AndIntLit16 = 0xd5,
    OrIntLit16 = 0xd6,
    XorIntLit16 = 0xd7,
    AddIntLit8 = 0xd8,
    RsubIntLit8 = 0xd9,
    MulIntLit8 = 0xda,
    DivIntLit8 = 0xdb,
    RemIntLit8 = 0xdc,
    AndIntLit8 = 0xdd,
    OrIntLit8 = 0xde,
    XorIntLit8 = 0xdf,
    ShlIntLit8 = 0xe0,
    ShrIntLit8 = 0xe1,
    UshrIntLit8 = 0xe2,
    // 0xe3-0xf9 unused
    InvokePolymorphic = 0xfa,
    InvokePolymorphicRange = 0xfb,
    InvokeCustom = 0xfc,
    InvokeCustomRange = 0xfd,
    ConstMethodHandle = 0xfe,
    ConstMethodType = 0xff,
}

impl Opcode {
    /// Try to convert a byte to an opcode
    pub fn from_u8(value: u8) -> Option<Self> {
        // Check for valid opcodes
        match value {
            0x00..=0x3d | 0x44..=0x72 | 0x74..=0x78 | 0x7b..=0xe2 | 0xfa..=0xff => {
                // Safety: We've verified the value is a valid opcode
                Some(unsafe { std::mem::transmute(value) })
            }
            _ => None,
        }
    }

    /// Get the instruction format for this opcode
    pub fn format(self) -> InsnFormat {
        use InsnFormat::*;
        use Opcode::*;

        match self {
            Nop | ReturnVoid => Format10x,

            Move | MoveWide | MoveObject => Format12x,
            MoveFrom16 | MoveWideFrom16 | MoveObjectFrom16 => Format22x,
            Move16 | MoveWide16 | MoveObject16 => Format32x,

            MoveResult | MoveResultWide | MoveResultObject | MoveException | Return
            | ReturnWide | ReturnObject | MonitorEnter | MonitorExit | Throw => Format11x,

            Const4 => Format11n,
            Const16 | ConstWide16 => Format21s,
            Const | ConstWide32 => Format31i,
            ConstHigh16 | ConstWideHigh16 => Format21h,
            ConstWide => Format51l,

            ConstString => Format21c,
            ConstStringJumbo => Format31c,
            ConstClass | CheckCast | NewInstance | ConstMethodHandle | ConstMethodType => {
                Format21c
            }

            InstanceOf | NewArray => Format22c,
            ArrayLength | NegInt | NotInt | NegLong | NotLong | NegFloat | NegDouble
            | IntToLong | IntToFloat | IntToDouble | LongToInt | LongToFloat | LongToDouble
            | FloatToInt | FloatToLong | FloatToDouble | DoubleToInt | DoubleToLong
            | DoubleToFloat | IntToByte | IntToChar | IntToShort => Format12x,

            FilledNewArray => Format35c,
            FilledNewArrayRange => Format3rc,
            FillArrayData | PackedSwitch | SparseSwitch => Format31t,

            Goto => Format10t,
            Goto16 => Format20t,
            Goto32 => Format30t,

            CmplFloat | CmpgFloat | CmplDouble | CmpgDouble | CmpLong => Format23x,

            IfEq | IfNe | IfLt | IfGe | IfGt | IfLe => Format22t,
            IfEqz | IfNez | IfLtz | IfGez | IfGtz | IfLez => Format21t,

            Aget | AgetWide | AgetObject | AgetBoolean | AgetByte | AgetChar | AgetShort
            | Aput | AputWide | AputObject | AputBoolean | AputByte | AputChar | AputShort => {
                Format23x
            }

            Iget | IgetWide | IgetObject | IgetBoolean | IgetByte | IgetChar | IgetShort
            | Iput | IputWide | IputObject | IputBoolean | IputByte | IputChar | IputShort => {
                Format22c
            }

            Sget | SgetWide | SgetObject | SgetBoolean | SgetByte | SgetChar | SgetShort
            | Sput | SputWide | SputObject | SputBoolean | SputByte | SputChar | SputShort => {
                Format21c
            }

            InvokeVirtual | InvokeSuper | InvokeDirect | InvokeStatic | InvokeInterface => {
                Format35c
            }
            InvokeVirtualRange | InvokeSuperRange | InvokeDirectRange | InvokeStaticRange
            | InvokeInterfaceRange => Format3rc,

            AddInt | SubInt | MulInt | DivInt | RemInt | AndInt | OrInt | XorInt | ShlInt
            | ShrInt | UshrInt | AddLong | SubLong | MulLong | DivLong | RemLong | AndLong
            | OrLong | XorLong | ShlLong | ShrLong | UshrLong | AddFloat | SubFloat | MulFloat
            | DivFloat | RemFloat | AddDouble | SubDouble | MulDouble | DivDouble | RemDouble => {
                Format23x
            }

            AddInt2Addr | SubInt2Addr | MulInt2Addr | DivInt2Addr | RemInt2Addr | AndInt2Addr
            | OrInt2Addr | XorInt2Addr | ShlInt2Addr | ShrInt2Addr | UshrInt2Addr
            | AddLong2Addr | SubLong2Addr | MulLong2Addr | DivLong2Addr | RemLong2Addr
            | AndLong2Addr | OrLong2Addr | XorLong2Addr | ShlLong2Addr | ShrLong2Addr
            | UshrLong2Addr | AddFloat2Addr | SubFloat2Addr | MulFloat2Addr | DivFloat2Addr
            | RemFloat2Addr | AddDouble2Addr | SubDouble2Addr | MulDouble2Addr
            | DivDouble2Addr | RemDouble2Addr => Format12x,

            AddIntLit16 | RsubInt | MulIntLit16 | DivIntLit16 | RemIntLit16 | AndIntLit16
            | OrIntLit16 | XorIntLit16 => Format22s,

            AddIntLit8 | RsubIntLit8 | MulIntLit8 | DivIntLit8 | RemIntLit8 | AndIntLit8
            | OrIntLit8 | XorIntLit8 | ShlIntLit8 | ShrIntLit8 | UshrIntLit8 => Format22b,

            InvokePolymorphic => Format45cc,
            InvokePolymorphicRange => Format4rcc,
            InvokeCustom => Format35c,
            InvokeCustomRange => Format3rc,
        }
    }

    /// Get the opcode name
    pub fn name(self) -> &'static str {
        use Opcode::*;
        match self {
            Nop => "nop",
            Move => "move",
            MoveFrom16 => "move/from16",
            Move16 => "move/16",
            MoveWide => "move-wide",
            MoveWideFrom16 => "move-wide/from16",
            MoveWide16 => "move-wide/16",
            MoveObject => "move-object",
            MoveObjectFrom16 => "move-object/from16",
            MoveObject16 => "move-object/16",
            MoveResult => "move-result",
            MoveResultWide => "move-result-wide",
            MoveResultObject => "move-result-object",
            MoveException => "move-exception",
            ReturnVoid => "return-void",
            Return => "return",
            ReturnWide => "return-wide",
            ReturnObject => "return-object",
            Const4 => "const/4",
            Const16 => "const/16",
            Const => "const",
            ConstHigh16 => "const/high16",
            ConstWide16 => "const-wide/16",
            ConstWide32 => "const-wide/32",
            ConstWide => "const-wide",
            ConstWideHigh16 => "const-wide/high16",
            ConstString => "const-string",
            ConstStringJumbo => "const-string/jumbo",
            ConstClass => "const-class",
            MonitorEnter => "monitor-enter",
            MonitorExit => "monitor-exit",
            CheckCast => "check-cast",
            InstanceOf => "instance-of",
            ArrayLength => "array-length",
            NewInstance => "new-instance",
            NewArray => "new-array",
            FilledNewArray => "filled-new-array",
            FilledNewArrayRange => "filled-new-array/range",
            FillArrayData => "fill-array-data",
            Throw => "throw",
            Goto => "goto",
            Goto16 => "goto/16",
            Goto32 => "goto/32",
            PackedSwitch => "packed-switch",
            SparseSwitch => "sparse-switch",
            CmplFloat => "cmpl-float",
            CmpgFloat => "cmpg-float",
            CmplDouble => "cmpl-double",
            CmpgDouble => "cmpg-double",
            CmpLong => "cmp-long",
            IfEq => "if-eq",
            IfNe => "if-ne",
            IfLt => "if-lt",
            IfGe => "if-ge",
            IfGt => "if-gt",
            IfLe => "if-le",
            IfEqz => "if-eqz",
            IfNez => "if-nez",
            IfLtz => "if-ltz",
            IfGez => "if-gez",
            IfGtz => "if-gtz",
            IfLez => "if-lez",
            Aget => "aget",
            AgetWide => "aget-wide",
            AgetObject => "aget-object",
            AgetBoolean => "aget-boolean",
            AgetByte => "aget-byte",
            AgetChar => "aget-char",
            AgetShort => "aget-short",
            Aput => "aput",
            AputWide => "aput-wide",
            AputObject => "aput-object",
            AputBoolean => "aput-boolean",
            AputByte => "aput-byte",
            AputChar => "aput-char",
            AputShort => "aput-short",
            Iget => "iget",
            IgetWide => "iget-wide",
            IgetObject => "iget-object",
            IgetBoolean => "iget-boolean",
            IgetByte => "iget-byte",
            IgetChar => "iget-char",
            IgetShort => "iget-short",
            Iput => "iput",
            IputWide => "iput-wide",
            IputObject => "iput-object",
            IputBoolean => "iput-boolean",
            IputByte => "iput-byte",
            IputChar => "iput-char",
            IputShort => "iput-short",
            Sget => "sget",
            SgetWide => "sget-wide",
            SgetObject => "sget-object",
            SgetBoolean => "sget-boolean",
            SgetByte => "sget-byte",
            SgetChar => "sget-char",
            SgetShort => "sget-short",
            Sput => "sput",
            SputWide => "sput-wide",
            SputObject => "sput-object",
            SputBoolean => "sput-boolean",
            SputByte => "sput-byte",
            SputChar => "sput-char",
            SputShort => "sput-short",
            InvokeVirtual => "invoke-virtual",
            InvokeSuper => "invoke-super",
            InvokeDirect => "invoke-direct",
            InvokeStatic => "invoke-static",
            InvokeInterface => "invoke-interface",
            InvokeVirtualRange => "invoke-virtual/range",
            InvokeSuperRange => "invoke-super/range",
            InvokeDirectRange => "invoke-direct/range",
            InvokeStaticRange => "invoke-static/range",
            InvokeInterfaceRange => "invoke-interface/range",
            NegInt => "neg-int",
            NotInt => "not-int",
            NegLong => "neg-long",
            NotLong => "not-long",
            NegFloat => "neg-float",
            NegDouble => "neg-double",
            IntToLong => "int-to-long",
            IntToFloat => "int-to-float",
            IntToDouble => "int-to-double",
            LongToInt => "long-to-int",
            LongToFloat => "long-to-float",
            LongToDouble => "long-to-double",
            FloatToInt => "float-to-int",
            FloatToLong => "float-to-long",
            FloatToDouble => "float-to-double",
            DoubleToInt => "double-to-int",
            DoubleToLong => "double-to-long",
            DoubleToFloat => "double-to-float",
            IntToByte => "int-to-byte",
            IntToChar => "int-to-char",
            IntToShort => "int-to-short",
            AddInt => "add-int",
            SubInt => "sub-int",
            MulInt => "mul-int",
            DivInt => "div-int",
            RemInt => "rem-int",
            AndInt => "and-int",
            OrInt => "or-int",
            XorInt => "xor-int",
            ShlInt => "shl-int",
            ShrInt => "shr-int",
            UshrInt => "ushr-int",
            AddLong => "add-long",
            SubLong => "sub-long",
            MulLong => "mul-long",
            DivLong => "div-long",
            RemLong => "rem-long",
            AndLong => "and-long",
            OrLong => "or-long",
            XorLong => "xor-long",
            ShlLong => "shl-long",
            ShrLong => "shr-long",
            UshrLong => "ushr-long",
            AddFloat => "add-float",
            SubFloat => "sub-float",
            MulFloat => "mul-float",
            DivFloat => "div-float",
            RemFloat => "rem-float",
            AddDouble => "add-double",
            SubDouble => "sub-double",
            MulDouble => "mul-double",
            DivDouble => "div-double",
            RemDouble => "rem-double",
            AddInt2Addr => "add-int/2addr",
            SubInt2Addr => "sub-int/2addr",
            MulInt2Addr => "mul-int/2addr",
            DivInt2Addr => "div-int/2addr",
            RemInt2Addr => "rem-int/2addr",
            AndInt2Addr => "and-int/2addr",
            OrInt2Addr => "or-int/2addr",
            XorInt2Addr => "xor-int/2addr",
            ShlInt2Addr => "shl-int/2addr",
            ShrInt2Addr => "shr-int/2addr",
            UshrInt2Addr => "ushr-int/2addr",
            AddLong2Addr => "add-long/2addr",
            SubLong2Addr => "sub-long/2addr",
            MulLong2Addr => "mul-long/2addr",
            DivLong2Addr => "div-long/2addr",
            RemLong2Addr => "rem-long/2addr",
            AndLong2Addr => "and-long/2addr",
            OrLong2Addr => "or-long/2addr",
            XorLong2Addr => "xor-long/2addr",
            ShlLong2Addr => "shl-long/2addr",
            ShrLong2Addr => "shr-long/2addr",
            UshrLong2Addr => "ushr-long/2addr",
            AddFloat2Addr => "add-float/2addr",
            SubFloat2Addr => "sub-float/2addr",
            MulFloat2Addr => "mul-float/2addr",
            DivFloat2Addr => "div-float/2addr",
            RemFloat2Addr => "rem-float/2addr",
            AddDouble2Addr => "add-double/2addr",
            SubDouble2Addr => "sub-double/2addr",
            MulDouble2Addr => "mul-double/2addr",
            DivDouble2Addr => "div-double/2addr",
            RemDouble2Addr => "rem-double/2addr",
            AddIntLit16 => "add-int/lit16",
            RsubInt => "rsub-int",
            MulIntLit16 => "mul-int/lit16",
            DivIntLit16 => "div-int/lit16",
            RemIntLit16 => "rem-int/lit16",
            AndIntLit16 => "and-int/lit16",
            OrIntLit16 => "or-int/lit16",
            XorIntLit16 => "xor-int/lit16",
            AddIntLit8 => "add-int/lit8",
            RsubIntLit8 => "rsub-int/lit8",
            MulIntLit8 => "mul-int/lit8",
            DivIntLit8 => "div-int/lit8",
            RemIntLit8 => "rem-int/lit8",
            AndIntLit8 => "and-int/lit8",
            OrIntLit8 => "or-int/lit8",
            XorIntLit8 => "xor-int/lit8",
            ShlIntLit8 => "shl-int/lit8",
            ShrIntLit8 => "shr-int/lit8",
            UshrIntLit8 => "ushr-int/lit8",
            InvokePolymorphic => "invoke-polymorphic",
            InvokePolymorphicRange => "invoke-polymorphic/range",
            InvokeCustom => "invoke-custom",
            InvokeCustomRange => "invoke-custom/range",
            ConstMethodHandle => "const-method-handle",
            ConstMethodType => "const-method-type",
        }
    }
}

impl std::fmt::Display for Opcode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}
