package androidx.compose.ui.layout;

import androidx.compose.ui.unit.ConstraintsKt;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import kotlin.Metadata;

/* loaded from: classes.dex */
@Metadata(d1 = "\u00006\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\u0008\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\u0008\u0004\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\u0008\u0005\u0008ç\u0080\u0001\u0018\u00002\u00020\u0001J(\u0010\u0002\u001a\u00020\u0003*\u00020\u00042\u0012\u0010\u0005\u001a\u000e\u0012\n\u0012\u0008\u0012\u0004\u0012\u00020\u00070\u00060\u00062\u0006\u0010\u0008\u001a\u00020\u0003H\u0016J(\u0010\t\u001a\u00020\u0003*\u00020\u00042\u0012\u0010\u0005\u001a\u000e\u0012\n\u0012\u0008\u0012\u0004\u0012\u00020\u00070\u00060\u00062\u0006\u0010\n\u001a\u00020\u0003H\u0016J2\u0010\u000b\u001a\u00020\u000c*\u00020\r2\u0012\u0010\u0005\u001a\u000e\u0012\n\u0012\u0008\u0012\u0004\u0012\u00020\u000e0\u00060\u00062\u0006\u0010\u000f\u001a\u00020\u0010H&ø\u0001\u0000¢\u0006\u0004\u0008\u0011\u0010\u0012J(\u0010\u0013\u001a\u00020\u0003*\u00020\u00042\u0012\u0010\u0005\u001a\u000e\u0012\n\u0012\u0008\u0012\u0004\u0012\u00020\u00070\u00060\u00062\u0006\u0010\u0008\u001a\u00020\u0003H\u0016J(\u0010\u0014\u001a\u00020\u0003*\u00020\u00042\u0012\u0010\u0005\u001a\u000e\u0012\n\u0012\u0008\u0012\u0004\u0012\u00020\u00070\u00060\u00062\u0006\u0010\n\u001a\u00020\u0003H\u0016ø\u0001\u0001\u0082\u0002\r\n\u0005\u0008¡\u001e0\u0001\n\u0004\u0008!0\u0001¨\u0006\u0015À\u0006\u0001", d2 = {"Landroidx/compose/ui/layout/MultiContentMeasurePolicy;", "", "maxIntrinsicHeight", "", "Landroidx/compose/ui/layout/IntrinsicMeasureScope;", "measurables", "", "Landroidx/compose/ui/layout/IntrinsicMeasurable;", "width", "maxIntrinsicWidth", "height", "measure", "Landroidx/compose/ui/layout/MeasureResult;", "Landroidx/compose/ui/layout/MeasureScope;", "Landroidx/compose/ui/layout/Measurable;", "constraints", "Landroidx/compose/ui/unit/Constraints;", "measure-3p2s80s", "(Landroidx/compose/ui/layout/MeasureScope;Ljava/util/List;J)Landroidx/compose/ui/layout/MeasureResult;", "minIntrinsicHeight", "minIntrinsicWidth", "ui_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
public interface MultiContentMeasurePolicy {
    public int maxIntrinsicHeight(androidx.compose.ui.layout.IntrinsicMeasureScope $this$maxIntrinsicHeight, List<? extends List<? extends androidx.compose.ui.layout.IntrinsicMeasurable>> measurables, int width) {
        Object obj6;
        Object obj4;
        int i4;
        int size;
        ArrayList arrayList;
        int target$iv;
        Object obj7;
        int i2;
        int index$iv$iv;
        Object obj3;
        Object obj;
        int i13;
        ArrayList list2;
        Object obj5;
        int i6;
        Object obj2;
        int i7;
        ArrayList arrayList2;
        Object obj9;
        int i;
        int i10;
        int i9;
        ArrayList list;
        int i8;
        int i5;
        Object $this$fastForEach$iv$iv;
        int i14;
        int i11;
        int i3;
        Object obj10;
        int i12;
        obj6 = measurables;
        i4 = 0;
        arrayList = new ArrayList(obj6.size());
        i2 = 0;
        index$iv$iv = 0;
        while (index$iv$iv < obj6.size()) {
            i13 = 0;
            i6 = 0;
            obj2 = obj5;
            i7 = 0;
            arrayList2 = new ArrayList(obj2.size());
            i = 0;
            size = obj2.size();
            target$iv = i10;
            while (target$iv < size) {
                i5 = 0;
                i11 = 0;
                DefaultIntrinsicMeasurable index$iv$iv2 = new DefaultIntrinsicMeasurable((IntrinsicMeasurable)obj4.get(target$iv), IntrinsicMinMax.Max, IntrinsicWidthHeight.Height);
                (Collection)arrayList2.add(index$iv$iv2);
                target$iv = i3 + 1;
                obj4 = $this$fastForEach$iv$iv;
                size = i14;
                obj7 = obj10;
                i2 = i12;
            }
            $this$fastForEach$iv$iv = obj4;
            i3 = target$iv;
            obj10 = obj7;
            i12 = i2;
            (Collection)arrayList.add((List)arrayList2);
            index$iv$iv++;
            obj6 = obj9;
            i4 = i9;
            arrayList = list;
            i5 = 0;
            i11 = 0;
            index$iv$iv2 = new DefaultIntrinsicMeasurable((IntrinsicMeasurable)obj4.get(target$iv), IntrinsicMinMax.Max, IntrinsicWidthHeight.Height);
            (Collection)arrayList2.add(index$iv$iv2);
            target$iv = i3 + 1;
            obj4 = $this$fastForEach$iv$iv;
            size = i14;
            obj7 = obj10;
            i2 = i12;
        }
        Object $this$fastMap$iv = obj6;
        int i22 = i4;
        Object obj11 = obj7;
        int i23 = i2;
        int i19 = 0;
        IntrinsicsMeasureScope intrinsicsMeasureScope = new IntrinsicsMeasureScope($this$maxIntrinsicHeight, $this$maxIntrinsicHeight.getLayoutDirection());
        return this.measure-3p2s80s((MeasureScope)intrinsicsMeasureScope, (List)arrayList, ConstraintsKt.Constraints$default(0, width, 0, i19, 13, 0)).getHeight();
    }

    public int maxIntrinsicWidth(androidx.compose.ui.layout.IntrinsicMeasureScope $this$maxIntrinsicWidth, List<? extends List<? extends androidx.compose.ui.layout.IntrinsicMeasurable>> measurables, int height) {
        Object obj6;
        Object obj;
        int i;
        int size;
        ArrayList arrayList;
        int target$iv;
        Object obj7;
        int i13;
        int index$iv$iv;
        Object obj4;
        Object obj5;
        int i14;
        ArrayList list2;
        Object obj2;
        int i12;
        Object obj3;
        int i6;
        ArrayList arrayList2;
        Object obj9;
        int i4;
        int i5;
        int i3;
        ArrayList list;
        int i7;
        int i8;
        Object $this$fastForEach$iv$iv;
        int i9;
        int i11;
        int i10;
        Object obj10;
        int i2;
        obj6 = measurables;
        i = 0;
        arrayList = new ArrayList(obj6.size());
        i13 = 0;
        index$iv$iv = 0;
        while (index$iv$iv < obj6.size()) {
            i14 = 0;
            i12 = 0;
            obj3 = obj2;
            i6 = 0;
            arrayList2 = new ArrayList(obj3.size());
            i4 = 0;
            size = obj3.size();
            target$iv = i5;
            while (target$iv < size) {
                i8 = 0;
                i11 = 0;
                DefaultIntrinsicMeasurable index$iv$iv2 = new DefaultIntrinsicMeasurable((IntrinsicMeasurable)obj.get(target$iv), IntrinsicMinMax.Max, IntrinsicWidthHeight.Width);
                (Collection)arrayList2.add(index$iv$iv2);
                target$iv = i10 + 1;
                obj = $this$fastForEach$iv$iv;
                size = i9;
                obj7 = obj10;
                i13 = i2;
            }
            $this$fastForEach$iv$iv = obj;
            i10 = target$iv;
            obj10 = obj7;
            i2 = i13;
            (Collection)arrayList.add((List)arrayList2);
            index$iv$iv++;
            obj6 = obj9;
            i = i3;
            arrayList = list;
            i8 = 0;
            i11 = 0;
            index$iv$iv2 = new DefaultIntrinsicMeasurable((IntrinsicMeasurable)obj.get(target$iv), IntrinsicMinMax.Max, IntrinsicWidthHeight.Width);
            (Collection)arrayList2.add(index$iv$iv2);
            target$iv = i10 + 1;
            obj = $this$fastForEach$iv$iv;
            size = i9;
            obj7 = obj10;
            i13 = i2;
        }
        Object $this$fastMap$iv = obj6;
        int i22 = i;
        Object obj11 = obj7;
        int i23 = i13;
        int i17 = 0;
        IntrinsicsMeasureScope intrinsicsMeasureScope = new IntrinsicsMeasureScope($this$maxIntrinsicWidth, $this$maxIntrinsicWidth.getLayoutDirection());
        return this.measure-3p2s80s((MeasureScope)intrinsicsMeasureScope, (List)arrayList, ConstraintsKt.Constraints$default(0, i17, 0, height, 7, 0)).getWidth();
    }

    public abstract androidx.compose.ui.layout.MeasureResult measure-3p2s80s(androidx.compose.ui.layout.MeasureScope measureScope, List<? extends List<? extends androidx.compose.ui.layout.Measurable>> list2, long l3);

    public int minIntrinsicHeight(androidx.compose.ui.layout.IntrinsicMeasureScope $this$minIntrinsicHeight, List<? extends List<? extends androidx.compose.ui.layout.IntrinsicMeasurable>> measurables, int width) {
        Object obj6;
        Object obj5;
        int i12;
        int size;
        ArrayList arrayList;
        int target$iv;
        Object obj7;
        int i;
        int index$iv$iv;
        Object obj;
        Object obj4;
        int i4;
        ArrayList list2;
        Object obj2;
        int i13;
        Object obj3;
        int i7;
        ArrayList arrayList2;
        Object obj9;
        int i10;
        int i9;
        int i8;
        ArrayList list;
        int i14;
        int i11;
        Object $this$fastForEach$iv$iv;
        int i2;
        int i6;
        int i5;
        Object obj10;
        int i3;
        obj6 = measurables;
        i12 = 0;
        arrayList = new ArrayList(obj6.size());
        i = 0;
        index$iv$iv = 0;
        while (index$iv$iv < obj6.size()) {
            i4 = 0;
            i13 = 0;
            obj3 = obj2;
            i7 = 0;
            arrayList2 = new ArrayList(obj3.size());
            i10 = 0;
            size = obj3.size();
            target$iv = i9;
            while (target$iv < size) {
                i11 = 0;
                i6 = 0;
                DefaultIntrinsicMeasurable index$iv$iv2 = new DefaultIntrinsicMeasurable((IntrinsicMeasurable)obj5.get(target$iv), IntrinsicMinMax.Min, IntrinsicWidthHeight.Height);
                (Collection)arrayList2.add(index$iv$iv2);
                target$iv = i5 + 1;
                obj5 = $this$fastForEach$iv$iv;
                size = i2;
                obj7 = obj10;
                i = i3;
            }
            $this$fastForEach$iv$iv = obj5;
            i5 = target$iv;
            obj10 = obj7;
            i3 = i;
            (Collection)arrayList.add((List)arrayList2);
            index$iv$iv++;
            obj6 = obj9;
            i12 = i8;
            arrayList = list;
            i11 = 0;
            i6 = 0;
            index$iv$iv2 = new DefaultIntrinsicMeasurable((IntrinsicMeasurable)obj5.get(target$iv), IntrinsicMinMax.Min, IntrinsicWidthHeight.Height);
            (Collection)arrayList2.add(index$iv$iv2);
            target$iv = i5 + 1;
            obj5 = $this$fastForEach$iv$iv;
            size = i2;
            obj7 = obj10;
            i = i3;
        }
        Object $this$fastMap$iv = obj6;
        int i22 = i12;
        Object obj11 = obj7;
        int i23 = i;
        int i19 = 0;
        IntrinsicsMeasureScope intrinsicsMeasureScope = new IntrinsicsMeasureScope($this$minIntrinsicHeight, $this$minIntrinsicHeight.getLayoutDirection());
        return this.measure-3p2s80s((MeasureScope)intrinsicsMeasureScope, (List)arrayList, ConstraintsKt.Constraints$default(0, width, 0, i19, 13, 0)).getHeight();
    }

    public int minIntrinsicWidth(androidx.compose.ui.layout.IntrinsicMeasureScope $this$minIntrinsicWidth, List<? extends List<? extends androidx.compose.ui.layout.IntrinsicMeasurable>> measurables, int height) {
        Object obj6;
        Object obj2;
        int i12;
        int size;
        ArrayList arrayList;
        int target$iv;
        Object obj7;
        int i11;
        int index$iv$iv;
        Object obj3;
        Object obj;
        int i7;
        ArrayList list;
        Object obj4;
        int i8;
        Object obj5;
        int i9;
        ArrayList arrayList2;
        Object obj9;
        int i4;
        int i14;
        int i5;
        ArrayList list2;
        int i13;
        int i;
        Object $this$fastForEach$iv$iv;
        int i10;
        int i2;
        int i6;
        Object obj10;
        int i3;
        obj6 = measurables;
        i12 = 0;
        arrayList = new ArrayList(obj6.size());
        i11 = 0;
        index$iv$iv = 0;
        while (index$iv$iv < obj6.size()) {
            i7 = 0;
            i8 = 0;
            obj5 = obj4;
            i9 = 0;
            arrayList2 = new ArrayList(obj5.size());
            i4 = 0;
            size = obj5.size();
            target$iv = i14;
            while (target$iv < size) {
                i = 0;
                i2 = 0;
                DefaultIntrinsicMeasurable index$iv$iv2 = new DefaultIntrinsicMeasurable((IntrinsicMeasurable)obj2.get(target$iv), IntrinsicMinMax.Min, IntrinsicWidthHeight.Width);
                (Collection)arrayList2.add(index$iv$iv2);
                target$iv = i6 + 1;
                obj2 = $this$fastForEach$iv$iv;
                size = i10;
                obj7 = obj10;
                i11 = i3;
            }
            $this$fastForEach$iv$iv = obj2;
            i6 = target$iv;
            obj10 = obj7;
            i3 = i11;
            (Collection)arrayList.add((List)arrayList2);
            index$iv$iv++;
            obj6 = obj9;
            i12 = i5;
            arrayList = list2;
            i = 0;
            i2 = 0;
            index$iv$iv2 = new DefaultIntrinsicMeasurable((IntrinsicMeasurable)obj2.get(target$iv), IntrinsicMinMax.Min, IntrinsicWidthHeight.Width);
            (Collection)arrayList2.add(index$iv$iv2);
            target$iv = i6 + 1;
            obj2 = $this$fastForEach$iv$iv;
            size = i10;
            obj7 = obj10;
            i11 = i3;
        }
        Object $this$fastMap$iv = obj6;
        int i22 = i12;
        Object obj11 = obj7;
        int i23 = i11;
        int i17 = 0;
        IntrinsicsMeasureScope intrinsicsMeasureScope = new IntrinsicsMeasureScope($this$minIntrinsicWidth, $this$minIntrinsicWidth.getLayoutDirection());
        return this.measure-3p2s80s((MeasureScope)intrinsicsMeasureScope, (List)arrayList, ConstraintsKt.Constraints$default(0, i17, 0, height, 7, 0)).getWidth();
    }
}
