package kotlin.i0.z.e.m0.m;

import java.util.Set;
import kotlin.d0.d.n;
import kotlin.i0.z.e.m0.f.e;
import kotlin.k0.h;
import kotlin.y.q0;

/* loaded from: classes3.dex */
public final class j {

    public static final e A;
    public static final e B;
    public static final e C;
    public static final e D;
    public static final e E;
    public static final Set<e> F;
    public static final Set<e> G;
    public static final Set<e> H;
    public static final e a;
    public static final e b;
    public static final e c;
    public static final e d;
    public static final e e;
    public static final e f;
    public static final e g;
    public static final e h;
    public static final e i;
    public static final e j;
    public static final e k;
    public static final e l;
    public static final h m;
    public static final e n;
    public static final e o;
    public static final e p;
    public static final e q;
    public static final e r;
    public static final e s;
    public static final e t;
    public static final e u;
    public static final e v;
    public static final e w;
    public static final e x;
    public static final e y;
    public static final e z;
    static {
        e eVar = e.j("getValue");
        n.e(eVar, "identifier(\"getValue\")");
        j.a = eVar;
        e eVar4 = e.j("setValue");
        n.e(eVar4, "identifier(\"setValue\")");
        j.b = eVar4;
        e eVar7 = e.j("provideDelegate");
        n.e(eVar7, "identifier(\"provideDelegate\")");
        j.c = eVar7;
        e eVar9 = e.j("equals");
        n.e(eVar9, "identifier(\"equals\")");
        j.d = eVar9;
        e eVar10 = e.j("compareTo");
        n.e(eVar10, "identifier(\"compareTo\")");
        j.e = eVar10;
        e eVar11 = e.j("contains");
        n.e(eVar11, "identifier(\"contains\")");
        j.f = eVar11;
        e eVar12 = e.j("invoke");
        n.e(eVar12, "identifier(\"invoke\")");
        j.g = eVar12;
        e eVar13 = e.j("iterator");
        n.e(eVar13, "identifier(\"iterator\")");
        j.h = eVar13;
        e eVar14 = e.j("get");
        n.e(eVar14, "identifier(\"get\")");
        j.i = eVar14;
        e eVar15 = e.j("set");
        n.e(eVar15, "identifier(\"set\")");
        j.j = eVar15;
        e eVar16 = e.j("next");
        n.e(eVar16, "identifier(\"next\")");
        j.k = eVar16;
        e eVar17 = e.j("hasNext");
        n.e(eVar17, "identifier(\"hasNext\")");
        j.l = eVar17;
        n.e(e.j("toString"), "identifier(\"toString\")");
        h hVar = new h("component\\d+");
        j.m = hVar;
        n.e(e.j("and"), "identifier(\"and\")");
        n.e(e.j("or"), "identifier(\"or\")");
        e eVar21 = e.j("inc");
        n.e(eVar21, "identifier(\"inc\")");
        j.n = eVar21;
        e eVar22 = e.j("dec");
        n.e(eVar22, "identifier(\"dec\")");
        j.o = eVar22;
        e eVar23 = e.j("plus");
        n.e(eVar23, "identifier(\"plus\")");
        j.p = eVar23;
        e eVar24 = e.j("minus");
        n.e(eVar24, "identifier(\"minus\")");
        j.q = eVar24;
        e eVar25 = e.j("not");
        n.e(eVar25, "identifier(\"not\")");
        j.r = eVar25;
        e eVar26 = e.j("unaryMinus");
        n.e(eVar26, "identifier(\"unaryMinus\")");
        j.s = eVar26;
        e eVar27 = e.j("unaryPlus");
        n.e(eVar27, "identifier(\"unaryPlus\")");
        j.t = eVar27;
        e eVar28 = e.j("times");
        n.e(eVar28, "identifier(\"times\")");
        j.u = eVar28;
        e eVar29 = e.j("div");
        n.e(eVar29, "identifier(\"div\")");
        j.v = eVar29;
        e eVar30 = e.j("mod");
        n.e(eVar30, "identifier(\"mod\")");
        j.w = eVar30;
        e eVar31 = e.j("rem");
        n.e(eVar31, "identifier(\"rem\")");
        j.x = eVar31;
        e eVar32 = e.j("rangeTo");
        n.e(eVar32, "identifier(\"rangeTo\")");
        j.y = eVar32;
        e eVar33 = e.j("timesAssign");
        n.e(eVar33, "identifier(\"timesAssign\")");
        j.z = eVar33;
        e eVar8 = e.j("divAssign");
        n.e(eVar8, "identifier(\"divAssign\")");
        j.A = eVar8;
        e eVar5 = e.j("modAssign");
        n.e(eVar5, "identifier(\"modAssign\")");
        j.B = eVar5;
        e eVar2 = e.j("remAssign");
        n.e(eVar2, "identifier(\"remAssign\")");
        j.C = eVar2;
        e eVar6 = e.j("plusAssign");
        n.e(eVar6, "identifier(\"plusAssign\")");
        j.D = eVar6;
        e eVar3 = e.j("minusAssign");
        n.e(eVar3, "identifier(\"minusAssign\")");
        j.E = eVar3;
        e[] arr = new e[5];
        final int i8 = 0;
        arr[i8] = eVar21;
        int i4 = 1;
        arr[i4] = eVar22;
        int i5 = 2;
        arr[i5] = eVar27;
        int i3 = 3;
        arr[i3] = eVar26;
        final int i9 = 4;
        arr[i9] = eVar25;
        q0.g(arr);
        e[] arr2 = new e[i3];
        arr2[i8] = eVar27;
        arr2[i4] = eVar26;
        arr2[i5] = eVar25;
        j.F = q0.g(arr2);
        e[] arr3 = new e[7];
        arr3[i8] = eVar28;
        arr3[i4] = eVar23;
        arr3[i5] = eVar24;
        arr3[i3] = eVar29;
        arr3[i9] = eVar30;
        int i6 = 5;
        arr3[i6] = eVar31;
        int i7 = 6;
        arr3[i7] = eVar32;
        j.G = q0.g(arr3);
        e[] arr4 = new e[i7];
        arr4[i8] = eVar33;
        arr4[i4] = eVar8;
        arr4[i5] = eVar5;
        arr4[i3] = eVar2;
        arr4[i9] = eVar6;
        arr4[i6] = eVar3;
        j.H = q0.g(arr4);
        e[] arr5 = new e[i3];
        arr5[i8] = eVar;
        arr5[i4] = eVar4;
        arr5[i5] = eVar7;
        q0.g(arr5);
    }
}
