package f.c.a.e;

import com.google.android.exoplayer2.audio.AudioSink.WriteException;
import com.google.firebase.database.snapshot.NamedNode;
import com.revenuecat.purchases.api.R.style;

/* loaded from: classes2.dex */
public final class l {

    public static final int[] A;
    public static final int A0 = 18;
    public static final int A1 = 6;
    public static final int A2 = 3;
    public static final int A3 = 0;
    public static final int A4 = 5;
    public static final int A5 = 14;
    public static final int A6 = 2;
    public static final int B = 1;
    public static final int B0 = 19;
    public static final int B1 = 7;
    public static final int B2 = 4;
    public static final int B3 = 1;
    public static final int B4 = 6;
    public static final int B5 = 15;
    public static final int C = 2;
    public static final int C0 = 20;
    public static final int C1 = 8;
    public static final int C2 = 6;
    public static final int C3 = 2;
    public static final int C4 = 7;
    public static final int C5 = 16;
    public static final int D = 3;
    public static final int D0 = 21;
    public static final int D1 = 9;
    public static final int D2 = 7;
    public static final int D3 = 3;
    public static final int D4 = 8;
    public static final int D5 = 17;
    public static final int E = 4;
    public static final int E0 = 22;
    public static final int E1 = 10;
    public static final int E2 = 8;
    public static final int E3 = 4;
    public static final int E4 = 9;
    public static final int E5 = 18;
    public static final int F = 5;
    public static final int F0 = 23;
    public static final int F1 = 11;
    public static final int F2 = 9;
    public static final int[] F3;
    public static final int F4 = 10;
    public static final int F5 = 19;
    public static final int G = 6;
    public static final int G0 = 24;
    public static final int G1 = 12;
    public static final int[] G2;
    public static final int G3 = 0;
    public static final int G4 = 11;
    public static final int G5 = 20;
    public static final int H = 7;
    public static final int H0 = 25;
    public static final int H1 = 15;
    public static final int H2 = 0;
    public static final int H3 = 1;
    public static final int H4 = 12;
    public static final int H5 = 21;
    public static final int I = 8;
    public static final int I0 = 26;
    public static final int I1 = 16;
    public static final int I2 = 1;
    public static final int I3 = 2;
    public static final int I4 = 13;
    public static final int I5 = 22;
    public static final int[] J;
    public static final int J0 = 27;
    public static final int[] J1;
    public static final int J2 = 2;
    public static final int J3 = 3;
    public static final int J4 = 14;
    public static final int J5 = 23;
    public static final int K = 0;
    public static final int K0 = 28;
    public static final int K1 = 0;
    public static final int K2 = 3;
    public static final int K3 = 4;
    public static final int K4 = 15;
    public static final int K5 = 24;
    public static final int L = 1;
    public static final int L0 = 29;
    public static final int[] L1;
    public static final int L2 = 4;
    public static final int L3 = 5;
    public static final int L4 = 16;
    public static final int L5 = 25;
    public static final int[] M;
    public static final int M0 = 30;
    public static final int M1 = 0;
    public static final int M2 = 5;
    public static final int M3 = 6;
    public static final int M4 = 17;
    public static final int M5 = 26;
    public static final int N = 0;
    public static final int N0 = 31;
    public static final int N1 = 1;
    public static final int N2 = 6;
    public static final int N3 = 7;
    public static final int N4 = 18;
    public static final int N5 = 27;
    public static final int O = 1;
    public static final int O0 = 32;
    public static final int[] O1;
    public static final int O2 = 7;
    public static final int O3 = 8;
    public static final int O4 = 19;
    public static final int O5 = 28;
    public static final int P = 2;
    public static final int P0 = 33;
    public static final int P1 = 0;
    public static final int P2 = 8;
    public static final int P3 = 9;
    public static final int P4 = 20;
    public static final int P5 = 29;
    public static final int Q = 3;
    public static final int Q0 = 34;
    public static final int Q1 = 1;
    public static final int Q2 = 9;
    public static final int Q3 = 10;
    public static final int Q4 = 21;
    public static final int Q5 = 30;
    public static final int R = 4;
    public static final int R0 = 35;
    public static final int R1 = 2;
    public static final int[] R2;
    public static final int R3 = 11;
    public static final int R4 = 22;
    public static final int R5 = 31;
    public static final int S = 5;
    public static final int S0 = 36;
    public static final int[] S1;
    public static final int S2 = 0;
    public static final int S3 = 12;
    public static final int S4 = 23;
    public static final int S5 = 32;
    public static final int T = 6;
    public static final int T0 = 37;
    public static final int T1 = 0;
    public static final int T2 = 1;
    public static final int T3 = 13;
    public static final int T4 = 24;
    public static final int T5 = 33;
    public static final int U = 7;
    public static final int U0 = 39;
    public static final int U1 = 1;
    public static final int U2 = 2;
    public static final int[] U3;
    public static final int U4 = 25;
    public static final int U5 = 34;
    public static final int V = 8;
    public static final int V0 = 40;
    public static final int V1 = 2;
    public static final int V2 = 3;
    public static final int V3 = 0;
    public static final int[] V4;
    public static final int V5 = 35;
    public static final int W = 9;
    public static final int W0 = 41;
    public static final int W1 = 3;
    public static final int W2 = 4;
    public static final int[] W3;
    public static final int W4 = 0;
    public static final int W5 = 36;
    public static final int X = 10;
    public static final int[] X0;
    public static final int[] X1;
    public static final int X2 = 5;
    public static final int X3 = 0;
    public static final int X4 = 1;
    public static final int X5 = 37;
    public static final int Y = 11;
    public static final int Y0 = 0;
    public static final int Y1 = 0;
    public static final int Y2 = 6;
    public static final int[] Y3;
    public static final int Y4 = 2;
    public static final int Y5 = 38;
    public static final int Z = 12;
    public static final int Z0 = 1;
    public static final int[] Z1;
    public static final int Z2 = 10;
    public static final int Z3 = 0;
    public static final int Z4 = 3;
    public static final int Z5 = 39;
    public static final int[] a;
    public static final int a0 = 13;
    public static final int a1 = 2;
    public static final int a2 = 0;
    public static final int a3 = 11;
    public static final int a4 = 1;
    public static final int a5 = 4;
    public static final int a6 = 40;
    public static final int b = 0;
    public static final int b0 = 14;
    public static final int b1 = 3;
    public static final int b2 = 1;
    public static final int[] b3;
    public static final int b4 = 2;
    public static final int b5 = 5;
    public static final int b6 = 41;
    public static final int c = 1;
    public static final int c0 = 15;
    public static final int c1 = 4;
    public static final int c2 = 2;
    public static final int c3 = 0;
    public static final int c4 = 3;
    public static final int c5 = 6;
    public static final int c6 = 42;
    public static final int d = 2;
    public static final int d0 = 16;
    public static final int d1 = 5;
    public static final int d2 = 3;
    public static final int d3 = 1;
    public static final int d4 = 4;
    public static final int d5 = 7;
    public static final int d6 = 43;
    public static final int e = 3;
    public static final int e0 = 17;
    public static final int e1 = 6;
    public static final int e2 = 4;
    public static final int[] e3;
    public static final int e4 = 5;
    public static final int e5 = 8;
    public static final int e6 = 44;
    public static final int f = 4;
    public static final int[] f0;
    public static final int[] f1;
    public static final int f2 = 5;
    public static final int f3 = 0;
    public static final int f4 = 6;
    public static final int f5 = 9;
    public static final int f6 = 45;
    public static final int g = 5;
    public static final int g0 = 3;
    public static final int g1 = 0;
    public static final int g2 = 6;
    public static final int g3 = 1;
    public static final int g4 = 7;
    public static final int g5 = 10;
    public static final int g6 = 46;
    public static final int h = 6;
    public static final int[] h0;
    public static final int h1 = 1;
    public static final int h2 = 7;
    public static final int[] h3;
    public static final int h4 = 8;
    public static final int h5 = 12;
    public static final int h6 = 47;
    public static final int i = 7;
    public static final int i0 = 0;
    public static final int i1 = 2;
    public static final int i2 = 8;
    public static final int i3 = 0;
    public static final int i4 = 9;
    public static final int i5 = 14;
    public static final int i6 = 48;
    public static final int[] j;
    public static final int j0 = 1;
    public static final int[] j1;
    public static final int j2 = 9;
    public static final int j3 = 1;
    public static final int[] j4;
    public static final int[] j5;
    public static final int j6 = 49;
    public static final int k = 0;
    public static final int k0 = 2;
    public static final int k1 = 0;
    public static final int k2 = 10;
    public static final int[] k3;
    public static final int k4 = 0;
    public static final int k5 = 0;
    public static final int k6 = 50;
    public static final int l = 1;
    public static final int l0 = 3;
    public static final int l1 = 1;
    public static final int l2 = 11;
    public static final int l3 = 0;
    public static final int l4 = 1;
    public static final int[] l5;
    public static final int l6 = 51;
    public static final int m = 2;
    public static final int m0 = 4;
    public static final int[] m1;
    public static final int m2 = 12;
    public static final int m3 = 1;
    public static final int m4 = 2;
    public static final int m5 = 0;
    public static final int m6 = 52;
    public static final int[] n;
    public static final int n0 = 5;
    public static final int n1 = 0;
    public static final int n2 = 13;
    public static final int n3 = 2;
    public static final int n4 = 3;
    public static final int n5 = 1;
    public static final int n6 = 53;
    public static final int o = 0;
    public static final int o0 = 6;
    public static final int o1 = 1;
    public static final int o2 = 14;
    public static final int[] o3;
    public static final int o4 = 4;
    public static final int o5 = 2;
    public static final int o6 = 54;
    public static final int p = 1;
    public static final int p0 = 7;
    public static final int p1 = 2;
    public static final int p2 = 15;
    public static final int p3 = 0;
    public static final int p4 = 5;
    public static final int p5 = 3;
    public static final int p6 = 57;
    public static final int q = 2;
    public static final int q0 = 8;
    public static final int[] q1;
    public static final int q2 = 16;
    public static final int q3 = 1;
    public static final int q4 = 6;
    public static final int q5 = 4;
    public static final int q6 = 58;
    public static final int r = 3;
    public static final int r0 = 9;
    public static final int r1 = 0;
    public static final int r2 = 19;
    public static final int r3 = 2;
    public static final int r4 = 7;
    public static final int r5 = 5;
    public static final int r6 = 59;
    public static final int s = 4;
    public static final int s0 = 10;
    public static final int s1 = 1;
    public static final int s2 = 20;
    public static final int[] s3;
    public static final int[] s4;
    public static final int s5 = 6;
    public static final int s6 = 60;
    public static final int t = 5;
    public static final int t0 = 11;
    public static final int[] t1;
    public static final int[] t2;
    public static final int t3 = 0;
    public static final int t4 = 0;
    public static final int t5 = 7;
    public static final int t6 = 61;
    public static final int u = 6;
    public static final int u0 = 12;
    public static final int u1 = 0;
    public static final int u2 = 0;
    public static final int u3 = 1;
    public static final int[] u4;
    public static final int u5 = 8;
    public static final int u6 = 62;
    public static final int v = 7;
    public static final int v0 = 13;
    public static final int v1 = 1;
    public static final int v2 = 1;
    public static final int[] v3;
    public static final int v4 = 0;
    public static final int v5 = 9;
    public static final int v6 = 63;
    public static final int w = 8;
    public static final int w0 = 14;
    public static final int w1 = 2;
    public static final int w2 = 2;
    public static final int w3 = 0;
    public static final int w4 = 1;
    public static final int w5 = 10;
    public static final int w6 = 64;
    public static final int x = 9;
    public static final int x0 = 15;
    public static final int x1 = 3;
    public static final int[] x2;
    public static final int x3 = 1;
    public static final int x4 = 2;
    public static final int x5 = 11;
    public static final int[] x6;
    public static final int y = 10;
    public static final int y0 = 16;
    public static final int y1 = 4;
    public static final int y2 = 1;
    public static final int y3 = 2;
    public static final int y4 = 3;
    public static final int y5 = 12;
    public static final int y6 = 0;
    public static final int z = 11;
    public static final int z0 = 17;
    public static final int z1 = 5;
    public static final int z2 = 2;
    public static final int[] z3;
    public static final int z4 = 4;
    public static final int z5 = 13;
    public static final int z6 = 1;
    static {
        l.a = new int[] { 0x010100d4 /* Unknown resource */, 0x0101048f /* Unknown resource */, 0x01010540 /* Unknown resource */, R.attr.elevation, R.attr.expanded, R.attr.liftOnScroll, R.attr.liftOnScrollTargetViewId, R.attr.statusBarForeground };
        l.j = new int[] { R.attr.layout_scrollEffect, R.attr.layout_scrollFlags, R.attr.layout_scrollInterpolator };
        l.n = new int[] { R.attr.backgroundColor, R.attr.badgeGravity, R.attr.badgeRadius, R.attr.badgeTextColor, R.attr.badgeWidePadding, R.attr.badgeWithTextRadius, R.attr.horizontalOffset, R.attr.horizontalOffsetWithText, R.attr.maxCharacterCount, R.attr.number, R.attr.verticalOffset, R.attr.verticalOffsetWithText };
        l.A = new int[] { 0x01010139 /* Unknown resource */, R.attr.hideAnimationBehavior, R.attr.indicatorColor, R.attr.minHideDelay, R.attr.showAnimationBehavior, R.attr.showDelay, R.attr.trackColor, R.attr.trackCornerRadius, R.attr.trackThickness };
        l.J = new int[] { 0x01010140 /* Unknown resource */, R.attr.itemHorizontalTranslationEnabled };
        l.M = new int[] { 0x0101011f /* Unknown resource */, 0x01010120 /* Unknown resource */, 0x01010440 /* Unknown resource */, R.attr.backgroundTint, R.attr.behavior_draggable, R.attr.behavior_expandedOffset, R.attr.behavior_fitToContents, R.attr.behavior_halfExpandedRatio, R.attr.behavior_hideable, R.attr.behavior_peekHeight, R.attr.behavior_saveFlags, R.attr.behavior_skipCollapsed, R.attr.gestureInsetBottomIgnored, R.attr.paddingBottomSystemWindowInsets, R.attr.paddingLeftSystemWindowInsets, R.attr.paddingRightSystemWindowInsets, R.attr.paddingTopSystemWindowInsets, R.attr.shapeAppearance, R.attr.shapeAppearanceOverlay };
        l.f0 = new int[] { 0x0101013f /* Unknown resource */, 0x01010140 /* Unknown resource */, R.attr.cardBackgroundColor, R.attr.cardCornerRadius, R.attr.cardElevation, R.attr.cardMaxElevation, R.attr.cardPreventCornerOverlap, R.attr.cardUseCompatPadding, R.attr.contentPadding, R.attr.contentPaddingBottom, R.attr.contentPaddingLeft, R.attr.contentPaddingRight, R.attr.contentPaddingTop };
        l.h0 = new int[] { 0x01010034 /* Unknown resource */, 0x01010095 /* Unknown resource */, 0x01010098 /* Unknown resource */, 0x010100ab /* Unknown resource */, 0x0101011f /* Unknown resource */, 0x0101014f /* Unknown resource */, 0x010101e5 /* Unknown resource */, R.attr.checkedIcon, R.attr.checkedIconEnabled, R.attr.checkedIconTint, R.attr.checkedIconVisible, R.attr.chipBackgroundColor, R.attr.chipCornerRadius, R.attr.chipEndPadding, R.attr.chipIcon, R.attr.chipIconEnabled, R.attr.chipIconSize, R.attr.chipIconTint, R.attr.chipIconVisible, R.attr.chipMinHeight, R.attr.chipMinTouchTargetSize, R.attr.chipStartPadding, R.attr.chipStrokeColor, R.attr.chipStrokeWidth, R.attr.chipSurfaceColor, R.attr.closeIcon, R.attr.closeIconEnabled, R.attr.closeIconEndPadding, R.attr.closeIconSize, R.attr.closeIconStartPadding, R.attr.closeIconTint, R.attr.closeIconVisible, R.attr.ensureMinTouchTargetSize, R.attr.hideMotionSpec, R.attr.iconEndPadding, R.attr.iconStartPadding, R.attr.rippleColor, R.attr.shapeAppearance, R.attr.shapeAppearanceOverlay, R.attr.showMotionSpec, R.attr.textEndPadding, R.attr.textStartPadding };
        l.X0 = new int[] { R.attr.checkedChip, R.attr.chipSpacing, R.attr.chipSpacingHorizontal, R.attr.chipSpacingVertical, R.attr.selectionRequired, R.attr.singleLine, R.attr.singleSelection };
        l.f1 = new int[] { R.attr.indicatorDirectionCircular, R.attr.indicatorInset, R.attr.indicatorSize };
        l.j1 = new int[] { R.attr.clockFaceBackgroundColor, R.attr.clockNumberTextColor };
        l.m1 = new int[] { R.attr.clockHandColor, R.attr.materialCircleRadius, R.attr.selectorSize };
        l.q1 = new int[] { R.attr.behavior_autoHide, R.attr.behavior_autoShrink };
        l.t1 = new int[] { 0x0101000e /* Unknown resource */, R.attr.backgroundTint, R.attr.backgroundTintMode, R.attr.borderWidth, R.attr.elevation, R.attr.ensureMinTouchTargetSize, R.attr.fabCustomSize, R.attr.fabSize, R.attr.hideMotionSpec, R.attr.hoveredFocusedTranslationZ, R.attr.maxImageSize, R.attr.pressedTranslationZ, R.attr.rippleColor, R.attr.shapeAppearance, R.attr.shapeAppearanceOverlay, R.attr.showMotionSpec, R.attr.useCompatPadding };
        int i22 = 1;
        int[] iArr35 = new int[i22];
        final int i28 = 0;
        iArr35[i28] = R.attr.behavior_autoHide;
        l.J1 = iArr35;
        l.L1 = new int[] { R.attr.itemSpacing, R.attr.lineSpacing };
        l.O1 = new int[] { 0x01010109 /* Unknown resource */, 0x01010200 /* Unknown resource */, R.attr.foregroundInsidePadding };
        l.S1 = new int[] { R.attr.backgroundInsetBottom, R.attr.backgroundInsetEnd, R.attr.backgroundInsetStart, R.attr.backgroundInsetTop };
        int[] iArr39 = new int[i22];
        iArr39[i28] = 0x01010220 /* Unknown resource */;
        l.X1 = iArr39;
        l.Z1 = new int[] { 0x010100d4 /* Unknown resource */, 0x010101b7 /* Unknown resource */, 0x010101b8 /* Unknown resource */, 0x010101b9 /* Unknown resource */, 0x010101ba /* Unknown resource */, 0x010101e5 /* Unknown resource */, R.attr.backgroundTint, R.attr.backgroundTintMode, R.attr.cornerRadius, R.attr.elevation, R.attr.icon, R.attr.iconGravity, R.attr.iconPadding, R.attr.iconSize, R.attr.iconTint, R.attr.iconTintMode, R.attr.rippleColor, R.attr.shapeAppearance, R.attr.shapeAppearanceOverlay, R.attr.strokeColor, R.attr.strokeWidth };
        l.t2 = new int[] { R.attr.checkedButton, R.attr.selectionRequired, R.attr.singleSelection };
        l.x2 = new int[] { 0x0101020d /* Unknown resource */, R.attr.dayInvalidStyle, R.attr.daySelectedStyle, R.attr.dayStyle, R.attr.dayTodayStyle, R.attr.nestedScrollable, R.attr.rangeFillColor, R.attr.yearSelectedStyle, R.attr.yearStyle, R.attr.yearTodayStyle };
        l.G2 = new int[] { 0x010101b7 /* Unknown resource */, 0x010101b8 /* Unknown resource */, 0x010101b9 /* Unknown resource */, 0x010101ba /* Unknown resource */, R.attr.itemFillColor, R.attr.itemShapeAppearance, R.attr.itemShapeAppearanceOverlay, R.attr.itemStrokeColor, R.attr.itemStrokeWidth, R.attr.itemTextColor };
        l.R2 = new int[] { 0x010101e5 /* Unknown resource */, R.attr.cardForegroundColor, R.attr.checkedIcon, R.attr.checkedIconMargin, R.attr.checkedIconSize, R.attr.checkedIconTint, R.attr.rippleColor, R.attr.shapeAppearance, R.attr.shapeAppearanceOverlay, R.attr.state_dragged, R.attr.strokeColor, R.attr.strokeWidth };
        l.b3 = new int[] { R.attr.buttonTint, R.attr.useMaterialThemeColors };
        l.e3 = new int[] { R.attr.buttonTint, R.attr.useMaterialThemeColors };
        l.h3 = new int[] { R.attr.shapeAppearance, R.attr.shapeAppearanceOverlay };
        l.k3 = new int[] { 0x010104b6 /* Unknown resource */, 0x0101057f /* Unknown resource */, R.attr.lineHeight };
        l.o3 = new int[] { 0x01010034 /* Unknown resource */, 0x0101057f /* Unknown resource */, R.attr.lineHeight };
        l.s3 = new int[] { R.attr.clockIcon, R.attr.keyboardIcon };
        l.v3 = new int[] { R.attr.navigationIconTint, R.attr.subtitleCentered, R.attr.titleCentered };
        l.z3 = new int[] { 0x01010155 /* Unknown resource */, 0x01010159 /* Unknown resource */, 0x010101a5 /* Unknown resource */, R.attr.marginHorizontal, R.attr.shapeAppearance };
        l.F3 = new int[] { R.attr.backgroundTint, R.attr.elevation, R.attr.itemActiveIndicatorStyle, R.attr.itemBackground, R.attr.itemIconSize, R.attr.itemIconTint, R.attr.itemPaddingBottom, R.attr.itemPaddingTop, R.attr.itemRippleColor, R.attr.itemTextAppearanceActive, R.attr.itemTextAppearanceInactive, R.attr.itemTextColor, R.attr.labelVisibilityMode, R.attr.menu };
        int[] iArr20 = new int[i22];
        iArr20[i28] = R.attr.materialCircleRadius;
        l.U3 = iArr20;
        int[] iArr21 = new int[i22];
        iArr21[i28] = R.attr.behavior_overlapTop;
        l.W3 = iArr21;
        l.Y3 = new int[] { R.attr.cornerFamily, R.attr.cornerFamilyBottomLeft, R.attr.cornerFamilyBottomRight, R.attr.cornerFamilyTopLeft, R.attr.cornerFamilyTopRight, R.attr.cornerSize, R.attr.cornerSizeBottomLeft, R.attr.cornerSizeBottomRight, R.attr.cornerSizeTopLeft, R.attr.cornerSizeTopRight };
        l.j4 = new int[] { 0x0101011f /* Unknown resource */, R.attr.actionTextColorAlpha, R.attr.animationMode, R.attr.backgroundOverlayColorAlpha, R.attr.backgroundTint, R.attr.backgroundTintMode, R.attr.elevation, R.attr.maxActionInlineWidth };
        int[] iArr2 = new int[i22];
        iArr2[i28] = R.attr.useMaterialThemeColors;
        l.s4 = iArr2;
        l.u4 = new int[] { R.attr.tabBackground, R.attr.tabContentStart, R.attr.tabGravity, R.attr.tabIconTint, R.attr.tabIconTintMode, R.attr.tabIndicator, R.attr.tabIndicatorAnimationDuration, R.attr.tabIndicatorAnimationMode, R.attr.tabIndicatorColor, R.attr.tabIndicatorFullWidth, R.attr.tabIndicatorGravity, R.attr.tabIndicatorHeight, R.attr.tabInlineLabel, R.attr.tabMaxWidth, R.attr.tabMinWidth, R.attr.tabMode, R.attr.tabPadding, R.attr.tabPaddingBottom, R.attr.tabPaddingEnd, R.attr.tabPaddingStart, R.attr.tabPaddingTop, R.attr.tabRippleColor, R.attr.tabSelectedTextColor, R.attr.tabTextAppearance, R.attr.tabTextColor, R.attr.tabUnboundedRipple };
        l.V4 = new int[] { 0x01010095 /* Unknown resource */, 0x01010096 /* Unknown resource */, 0x01010097 /* Unknown resource */, 0x01010098 /* Unknown resource */, 0x0101009a /* Unknown resource */, 0x0101009b /* Unknown resource */, 0x01010161 /* Unknown resource */, 0x01010162 /* Unknown resource */, 0x01010163 /* Unknown resource */, 0x01010164 /* Unknown resource */, 0x010103ac /* Unknown resource */, 0x01010585 /* Unknown resource */, R.attr.fontFamily, R.attr.fontVariationSettings, R.attr.textAllCaps, R.attr.textLocale };
        int[] iArr5 = new int[i22];
        iArr5[i28] = R.attr.textInputLayoutFocusedRectEnabled;
        l.j5 = iArr5;
        l.l5 = new int[] { 0x0101000e /* Unknown resource */, 0x0101009a /* Unknown resource */, 0x0101011f /* Unknown resource */, 0x0101013f /* Unknown resource */, 0x01010150 /* Unknown resource */, R.attr.boxBackgroundColor, R.attr.boxBackgroundMode, R.attr.boxCollapsedPaddingTop, R.attr.boxCornerRadiusBottomEnd, R.attr.boxCornerRadiusBottomStart, R.attr.boxCornerRadiusTopEnd, R.attr.boxCornerRadiusTopStart, R.attr.boxStrokeColor, R.attr.boxStrokeErrorColor, R.attr.boxStrokeWidth, R.attr.boxStrokeWidthFocused, R.attr.counterEnabled, R.attr.counterMaxLength, R.attr.counterOverflowTextAppearance, R.attr.counterOverflowTextColor, R.attr.counterTextAppearance, R.attr.counterTextColor, R.attr.endIconCheckable, R.attr.endIconContentDescription, R.attr.endIconDrawable, R.attr.endIconMode, R.attr.endIconTint, R.attr.endIconTintMode, R.attr.errorContentDescription, R.attr.errorEnabled, R.attr.errorIconDrawable, R.attr.errorIconTint, R.attr.errorIconTintMode, R.attr.errorTextAppearance, R.attr.errorTextColor, R.attr.expandedHintEnabled, R.attr.helperText, R.attr.helperTextEnabled, R.attr.helperTextTextAppearance, R.attr.helperTextTextColor, R.attr.hintAnimationEnabled, R.attr.hintEnabled, R.attr.hintTextAppearance, R.attr.hintTextColor, R.attr.passwordToggleContentDescription, R.attr.passwordToggleDrawable, R.attr.passwordToggleEnabled, R.attr.passwordToggleTint, R.attr.passwordToggleTintMode, R.attr.placeholderText, R.attr.placeholderTextAppearance, R.attr.placeholderTextColor, R.attr.prefixText, R.attr.prefixTextAppearance, R.attr.prefixTextColor, R.attr.shapeAppearance, R.attr.shapeAppearanceOverlay, R.attr.startIconCheckable, R.attr.startIconContentDescription, R.attr.startIconDrawable, R.attr.startIconTint, R.attr.startIconTintMode, R.attr.suffixText, R.attr.suffixTextAppearance, R.attr.suffixTextColor };
        l.x6 = new int[] { 0x01010034 /* Unknown resource */, R.attr.enforceMaterialTheme, R.attr.enforceTextAppearance };
    }
}
