package androidx.compose.foundation.gestures;

import _COROUTINE.CoroutineDebuggingKt;
import androidx.compose.ui.Modifier;
import androidx.compose.ui.geometry.Offset;
import androidx.compose.ui.geometry.Offset.Companion;
import androidx.compose.ui.input.pointer.AwaitPointerEventScope;
import androidx.compose.ui.input.pointer.PointerEvent;
import androidx.compose.ui.input.pointer.PointerEventKt;
import androidx.compose.ui.input.pointer.PointerEventPass;
import androidx.compose.ui.input.pointer.PointerInputChange;
import androidx.compose.ui.platform.ViewConfiguration;
import java.util.List;
import kotlin.Metadata;
import kotlin.ResultKt;
import kotlin.Unit;
import kotlin.coroutines.Continuation;
import kotlin.coroutines.intrinsics.IntrinsicsKt;
import kotlin.jvm.functions.Function1;
import kotlinx.coroutines.channels.Channel;

/* loaded from: classes.dex */
@Metadata(d1 = "\u00006\n\u0000\n\u0002\u0010\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000b\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0008\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\u0008\u0003\u001a<\u0010\u0000\u001a\u00020\u0001*\u00020\u00022\u0006\u0010\u0003\u001a\u00020\u00042\u000c\u0010\u0005\u001a\u0008\u0012\u0004\u0012\u00020\u00070\u00062\u0012\u0010\u0008\u001a\u000e\u0012\u0004\u0012\u00020\n\u0012\u0004\u0012\u00020\u00040\tH\u0082@¢\u0006\u0002\u0010\u000b\u001a<\u0010\u000c\u001a\u00020\r*\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0012\u0010\u0008\u001a\u000e\u0012\u0004\u0012\u00020\n\u0012\u0004\u0012\u00020\u00040\t2\u0008\u0008\u0002\u0010\u0010\u001a\u00020\u00042\u0008\u0008\u0002\u0010\u0011\u001a\u00020\u0004H\u0007\u001a&\u0010\u000c\u001a\u00020\r*\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0008\u0008\u0002\u0010\u0010\u001a\u00020\u00042\u0008\u0008\u0002\u0010\u0011\u001a\u00020\u0004¨\u0006\u0012", d2 = {"detectZoom", "", "Landroidx/compose/ui/input/pointer/AwaitPointerEventScope;", "panZoomLock", "", "channel", "Lkotlinx/coroutines/channels/Channel;", "Landroidx/compose/foundation/gestures/TransformEvent;", "canPan", "Lkotlin/Function1;", "Landroidx/compose/ui/geometry/Offset;", "(Landroidx/compose/ui/input/pointer/AwaitPointerEventScope;ZLkotlinx/coroutines/channels/Channel;Lkotlin/jvm/functions/Function1;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", "transformable", "Landroidx/compose/ui/Modifier;", "state", "Landroidx/compose/foundation/gestures/TransformableState;", "lockRotationOnZoomPan", "enabled", "foundation_release"}, k = 2, mv = {1, 8, 0}, xi = 48)
public final class TransformableKt {
    public static final Object access$detectZoom(AwaitPointerEventScope $receiver, boolean panZoomLock, Channel channel, Function1 canPan, Continuation $completion) {
        return TransformableKt.detectZoom($receiver, panZoomLock, channel, canPan, $completion);
    }

    private static final Object detectZoom(AwaitPointerEventScope awaitPointerEventScope, boolean z2, Channel<androidx.compose.foundation.gestures.TransformEvent> channel3, Function1<? super Offset, Boolean> function14, Continuation<? super Unit> continuation5) {
        Object obj3;
        Object $result;
        int $this$fastForEach$iv$iv2;
        int $this$fastForEach$iv$iv;
        int $this$fastForEach$iv$iv3;
        Object anon;
        Object obj2;
        int rotationChange;
        int zoom3;
        Object pastTouchSlop;
        int size;
        Object cOROUTINE_SUSPENDED;
        int i;
        int $this$detectZoom;
        Object canceled;
        int index$iv$iv;
        int i2;
        float f$2;
        int touchSlop3;
        int lockedToPanZoom3;
        long changes;
        int i3;
        int lockedToPanZoom2;
        int lockedToPanZoom;
        float f;
        int touchSlop;
        float $continuation;
        androidx.compose.foundation.gestures.TransformableKt.detectZoom.1 touchSlop2;
        long pastTouchSlop2;
        androidx.compose.foundation.gestures.TransformableKt.detectZoom.1 pan;
        int $continuation2;
        int zoom2;
        long l;
        int zoomMotion;
        int index$iv;
        float pan2;
        int channel2;
        int pan3;
        float rotation2;
        long $this$detectZoom2;
        boolean z$0;
        float rotation;
        Object panZoomLock2;
        boolean canPan;
        Object rotation3;
        float channel4;
        Object channel;
        Object panZoomLock;
        Object event;
        int l$2;
        float distance-impl;
        float obj;
        int transformDelta;
        int zoom;
        int positionChanged;
        int it2;
        int i6;
        boolean it3;
        int it;
        int i5;
        long l2;
        Object obj27;
        boolean obj28;
        Object obj29;
        Object obj30;
        obj3 = continuation5;
        anon = obj3;
        i2 = Integer.MIN_VALUE;
        if (obj3 instanceof TransformableKt.detectZoom.1 && label3 &= i2 != 0) {
            anon = obj3;
            i2 = Integer.MIN_VALUE;
            if (label3 &= i2 != 0) {
                anon.label = label -= i2;
            } else {
                anon = new TransformableKt.detectZoom.1(obj3);
            }
        } else {
        }
        touchSlop2 = anon;
        $result = touchSlop2.result;
        cOROUTINE_SUSPENDED = IntrinsicsKt.getCOROUTINE_SUSPENDED();
        switch (label2) {
            case 0:
                ResultKt.throwOnFailure($result);
                Object obj4 = awaitPointerEventScope;
                long zero-F1C5BW02 = Offset.Companion.getZero-F1C5BW0();
                l$2 = 0;
                float touchSlop4 = obj4.getViewConfiguration().getTouchSlop();
                int i9 = 0;
                touchSlop2.L$0 = obj4;
                touchSlop2.L$1 = channel3;
                touchSlop2.L$2 = function14;
                touchSlop2.Z$0 = z2;
                touchSlop2.F$0 = 0;
                touchSlop2.F$1 = 1065353216;
                touchSlop2.J$0 = zero-F1C5BW02;
                touchSlop2.I$0 = l$2;
                touchSlop2.F$2 = touchSlop4;
                touchSlop2.I$1 = i9;
                touchSlop2.label = 1;
                return cOROUTINE_SUSPENDED;
                pastTouchSlop2 = zero-F1C5BW02;
                lockedToPanZoom = l$2;
                f$2 = obj;
                channel = obj4;
                $this$detectZoom = zoom;
                break;
            case 1:
                $this$detectZoom = touchSlop2.I$1;
                f$2 = touchSlop2.F$2;
                lockedToPanZoom = touchSlop2.I$0;
                pastTouchSlop2 = touchSlop2.J$0;
                channel2 = touchSlop2.F$1;
                pan3 = touchSlop2.F$0;
                z$0 = touchSlop2.Z$0;
                panZoomLock2 = touchSlop2.L$2;
                rotation3 = touchSlop2.L$1;
                channel = touchSlop2.L$0;
                ResultKt.throwOnFailure($result);
                break;
            case 2:
                lockedToPanZoom = touchSlop2.I$0;
                rotation3 = touchSlop2.L$1;
                channel = touchSlop2.L$0;
                ResultKt.throwOnFailure($result);
                l$2 = l$22;
                canPan = z$02;
                rotation = f$0;
                rotation2 = channel2;
                l = j$0;
                pan = touchSlop2;
                $continuation = f$22;
                touchSlop3 = canceled3;
                canceled = cOROUTINE_SUSPENDED;
                obj2 = $result;
                touchSlop2.L$0 = channel;
                touchSlop2.L$1 = rotation3;
                touchSlop2.L$2 = panZoomLock2;
                int i17 = 0;
                touchSlop2.L$3 = i17;
                touchSlop2.Z$0 = z$0;
                touchSlop2.F$0 = pan3;
                touchSlop2.F$1 = channel2;
                touchSlop2.J$0 = pastTouchSlop2;
                touchSlop2.I$0 = lockedToPanZoom;
                touchSlop2.F$2 = f$2;
                touchSlop2.I$1 = $this$detectZoom;
                touchSlop2.label = 2;
                event = AwaitPointerEventScope.awaitPointerEvent$default(channel, i17, touchSlop2, 1, i17);
                return cOROUTINE_SUSPENDED;
                l$2 = panZoomLock2;
                canPan = z$0;
                rotation = pan3;
                rotation2 = channel2;
                l = pastTouchSlop2;
                pan = touchSlop2;
                $continuation = f$2;
                touchSlop3 = $this$detectZoom;
                canceled = cOROUTINE_SUSPENDED;
                obj2 = $result;
                $result = event;
                Object obj5 = $result;
                List changes2 = (PointerEvent)obj5.getChanges();
                transformDelta = 0;
                zoom = 0;
                obj28 = touchSlop3;
                lockedToPanZoom3 = positionChanged;
                i6 = 0;
                it = 0;
                $this$fastForEach$iv$iv2 = 1;
                lockedToPanZoom3++;
                $this$fastForEach$iv$iv2 = 0;
                zoom = TransformGestureDetectorKt.calculateZoom(obj5);
                float rotation4 = TransformGestureDetectorKt.calculateRotation(obj5);
                obj29 = lockedToPanZoom;
                changes = TransformGestureDetectorKt.calculatePan(obj5);
                rotation2 *= zoom;
                rotation += rotation4;
                obj30 = rotation4;
                float centroidSize = TransformGestureDetectorKt.calculateCentroidSize(obj5, false);
                positionChanged = pan4;
                int i7 = 1;
                float f4 = Math.abs(i15 /= i20);
                channel2 = obj28;
                index$iv = obj29;
                rotationChange = zoom4;
                it = rotation;
                $this$detectZoom2 = positionChanged;
                index$iv = 1;
                channel2 = i7;
                channel2 = 0;
                rotation3.trySend-JP2dKIU(TransformEvent.TransformStarted.INSTANCE);
                rotationChange = zoom4;
                it = rotation;
                $this$detectZoom2 = positionChanged;
                obj30 = rotation4;
                rotationChange = rotation2;
                it = rotation;
                $this$detectZoom2 = l;
                channel2 = obj28;
                index$iv = obj29;
                int i21 = 0;
                i6 = i21;
                i6 = obj30;
                transformDelta = 1;
                transformDelta = 0;
                transformDelta = 1;
                transformDelta = 0;
                obj29 = index$iv;
                obj28 = channel2;
                obj29 = index$iv;
                obj28 = channel2;
                obj29 = index$iv;
                obj28 = channel2;
                transformDelta = new TransformEvent.TransformDelta(zoom, changes, it2, i6, 0);
                rotation3.trySend-JP2dKIU(transformDelta);
                changes = obj5.getChanges();
                lockedToPanZoom = 0;
                index$iv = 0;
                transformDelta = changes.get(index$iv);
                zoom = 0.0f;
                transformDelta.consume();
                index$iv++;
                positionChanged = changes;
                obj29 = index$iv;
                obj28 = channel2;
                pan2 = rotationChange;
                f = it;
                i3 = obj28;
                zoom3 = obj29;
                rotation3.trySend-JP2dKIU(TransformEvent.TransformStopped.INSTANCE);
                f = rotation;
                pan2 = rotation2;
                $this$detectZoom2 = l2;
                i3 = obj28;
                zoom3 = obj29;
                pan.L$0 = channel;
                pan.L$1 = rotation3;
                pan.L$2 = l$2;
                pan.L$3 = obj5;
                pan.Z$0 = canPan;
                pan.F$0 = f;
                pan.F$1 = pan2;
                pan.J$0 = $this$detectZoom2;
                pan.I$0 = zoom3;
                pan.F$2 = $continuation;
                pan.I$1 = i3;
                pan.I$2 = $this$fastForEach$iv$iv2;
                pan.label = 3;
                return canceled;
                channel2 = pan2;
                obj = obj5;
                zoom2 = pan;
                event = channel;
                $continuation2 = zoom3;
                panZoomLock = rotation3;
                pastTouchSlop = obj27;
                channel4 = f;
                touchSlop = i3;
                lockedToPanZoom2 = obj28;
                List finalEvent = (PointerEvent)$result.getChanges();
                zoom = 0;
                positionChanged = 0;
                index$iv$iv = it2;
                it3 = false;
                i5 = 0;
                $this$fastForEach$iv$iv = 1;
                index$iv$iv++;
                $this$fastForEach$iv$iv = 0;
                $this$fastForEach$iv$iv3 = 1;
                $this$fastForEach$iv$iv3 = 0;
                List finallyCanceled = obj.getChanges();
                index$iv$iv = 0;
                lockedToPanZoom2 = 0;
                obj29 = i8;
                positionChanged = 0;
                i6 = 0;
                $this$fastForEach$iv$iv3 = 1;
                lockedToPanZoom2++;
                $this$fastForEach$iv$iv3 = 0;
                $result = obj27;
                cOROUTINE_SUSPENDED = obj28;
                $this$detectZoom = touchSlop;
                f$2 = $continuation;
                lockedToPanZoom = $continuation2;
                touchSlop2 = zoom2;
                pastTouchSlop2 = $this$detectZoom2;
                z$0 = canPan;
                pan3 = channel4;
                rotation3 = panZoomLock;
                channel = event;
                panZoomLock2 = l$2;
                return Unit.INSTANCE;
            case 3:
                $continuation2 = touchSlop2.I$0;
                channel4 = touchSlop2.F$0;
                l$2 = touchSlop2.L$2;
                ResultKt.throwOnFailure($result);
                obj = l$3;
                event = l$0;
                $this$detectZoom2 = rotation;
                canPan = z$03;
                panZoomLock = l$1;
                channel2 = f$1;
                zoom2 = touchSlop2;
                $continuation = f$23;
                touchSlop = i$1;
                lockedToPanZoom2 = i$2;
                canceled = cOROUTINE_SUSPENDED;
                pastTouchSlop = $result;
                touchSlop2.L$0 = channel;
                touchSlop2.L$1 = rotation3;
                touchSlop2.L$2 = panZoomLock2;
                i17 = 0;
                touchSlop2.L$3 = i17;
                touchSlop2.Z$0 = z$0;
                touchSlop2.F$0 = pan3;
                touchSlop2.F$1 = channel2;
                touchSlop2.J$0 = pastTouchSlop2;
                touchSlop2.I$0 = lockedToPanZoom;
                touchSlop2.F$2 = f$2;
                touchSlop2.I$1 = $this$detectZoom;
                touchSlop2.label = 2;
                event = AwaitPointerEventScope.awaitPointerEvent$default(channel, i17, touchSlop2, 1, i17);
                return cOROUTINE_SUSPENDED;
                l$2 = panZoomLock2;
                canPan = z$0;
                rotation = pan3;
                rotation2 = channel2;
                l = pastTouchSlop2;
                pan = touchSlop2;
                $continuation = f$2;
                touchSlop3 = $this$detectZoom;
                canceled = cOROUTINE_SUSPENDED;
                obj2 = $result;
                $result = event;
                obj5 = $result;
                changes2 = (PointerEvent)obj5.getChanges();
                transformDelta = 0;
                zoom = 0;
                obj28 = touchSlop3;
                lockedToPanZoom3 = positionChanged;
                i6 = 0;
                it = 0;
                $this$fastForEach$iv$iv2 = 1;
                lockedToPanZoom3++;
                $this$fastForEach$iv$iv2 = 0;
                zoom = TransformGestureDetectorKt.calculateZoom(obj5);
                rotation4 = TransformGestureDetectorKt.calculateRotation(obj5);
                obj29 = lockedToPanZoom;
                changes = TransformGestureDetectorKt.calculatePan(obj5);
                rotation2 *= zoom;
                rotation += rotation4;
                obj30 = rotation4;
                centroidSize = TransformGestureDetectorKt.calculateCentroidSize(obj5, false);
                positionChanged = pan4;
                i7 = 1;
                f4 = Math.abs(i15 /= i20);
                channel2 = obj28;
                index$iv = obj29;
                rotationChange = zoom4;
                it = rotation;
                $this$detectZoom2 = positionChanged;
                index$iv = 1;
                channel2 = i7;
                channel2 = 0;
                rotation3.trySend-JP2dKIU(TransformEvent.TransformStarted.INSTANCE);
                rotationChange = zoom4;
                it = rotation;
                $this$detectZoom2 = positionChanged;
                obj30 = rotation4;
                rotationChange = rotation2;
                it = rotation;
                $this$detectZoom2 = l;
                channel2 = obj28;
                index$iv = obj29;
                i21 = 0;
                i6 = i21;
                i6 = obj30;
                transformDelta = 1;
                transformDelta = 0;
                transformDelta = 1;
                transformDelta = 0;
                obj29 = index$iv;
                obj28 = channel2;
                obj29 = index$iv;
                obj28 = channel2;
                obj29 = index$iv;
                obj28 = channel2;
                transformDelta = new TransformEvent.TransformDelta(zoom, changes, it2, i6, 0);
                rotation3.trySend-JP2dKIU(transformDelta);
                changes = obj5.getChanges();
                lockedToPanZoom = 0;
                index$iv = 0;
                transformDelta = changes.get(index$iv);
                zoom = 0.0f;
                transformDelta.consume();
                index$iv++;
                positionChanged = changes;
                obj29 = index$iv;
                obj28 = channel2;
                pan2 = rotationChange;
                f = it;
                i3 = obj28;
                zoom3 = obj29;
                rotation3.trySend-JP2dKIU(TransformEvent.TransformStopped.INSTANCE);
                f = rotation;
                pan2 = rotation2;
                $this$detectZoom2 = l2;
                i3 = obj28;
                zoom3 = obj29;
                pan.L$0 = channel;
                pan.L$1 = rotation3;
                pan.L$2 = l$2;
                pan.L$3 = obj5;
                pan.Z$0 = canPan;
                pan.F$0 = f;
                pan.F$1 = pan2;
                pan.J$0 = $this$detectZoom2;
                pan.I$0 = zoom3;
                pan.F$2 = $continuation;
                pan.I$1 = i3;
                pan.I$2 = $this$fastForEach$iv$iv2;
                pan.label = 3;
                return canceled;
                channel2 = pan2;
                obj = obj5;
                zoom2 = pan;
                event = channel;
                $continuation2 = zoom3;
                panZoomLock = rotation3;
                pastTouchSlop = obj27;
                channel4 = f;
                touchSlop = i3;
                lockedToPanZoom2 = obj28;
                finalEvent = (PointerEvent)$result.getChanges();
                zoom = 0;
                positionChanged = 0;
                index$iv$iv = it2;
                it3 = false;
                i5 = 0;
                $this$fastForEach$iv$iv = 1;
                index$iv$iv++;
                $this$fastForEach$iv$iv = 0;
                $this$fastForEach$iv$iv3 = 1;
                $this$fastForEach$iv$iv3 = 0;
                finallyCanceled = obj.getChanges();
                index$iv$iv = 0;
                lockedToPanZoom2 = 0;
                obj29 = i8;
                positionChanged = 0;
                i6 = 0;
                $this$fastForEach$iv$iv3 = 1;
                lockedToPanZoom2++;
                $this$fastForEach$iv$iv3 = 0;
                $result = obj27;
                cOROUTINE_SUSPENDED = obj28;
                $this$detectZoom = touchSlop;
                f$2 = $continuation;
                lockedToPanZoom = $continuation2;
                touchSlop2 = zoom2;
                pastTouchSlop2 = $this$detectZoom2;
                z$0 = canPan;
                pan3 = channel4;
                rotation3 = panZoomLock;
                channel = event;
                panZoomLock2 = l$2;
                return Unit.INSTANCE;
            default:
                IllegalStateException $result2 = new IllegalStateException("call to 'resume' before 'invoke' with coroutine");
                throw $result2;
        }
    }

    public static final Modifier transformable(Modifier $this$transformable, androidx.compose.foundation.gestures.TransformableState state, Function1<? super Offset, Boolean> canPan, boolean lockRotationOnZoomPan, boolean enabled) {
        TransformableElement transformableElement = new TransformableElement(state, canPan, lockRotationOnZoomPan, enabled);
        return $this$transformable.then((Modifier)transformableElement);
    }

    public static final Modifier transformable(Modifier $this$transformable, androidx.compose.foundation.gestures.TransformableState state, boolean lockRotationOnZoomPan, boolean enabled) {
        return TransformableKt.transformable($this$transformable, state, (Function1)TransformableKt.transformable.1.INSTANCE, lockRotationOnZoomPan, enabled);
    }

    public static Modifier transformable$default(Modifier modifier, androidx.compose.foundation.gestures.TransformableState transformableState2, Function1 function13, boolean z4, boolean z5, int i6, Object object7) {
        int obj3;
        int obj4;
        if (i6 & 4 != 0) {
            obj3 = 0;
        }
        if (i6 &= 8 != 0) {
            obj4 = 1;
        }
        return TransformableKt.transformable(modifier, transformableState2, function13, obj3, obj4);
    }

    public static Modifier transformable$default(Modifier modifier, androidx.compose.foundation.gestures.TransformableState transformableState2, boolean z3, boolean z4, int i5, Object object6) {
        int obj2;
        int obj3;
        if (i5 & 2 != 0) {
            obj2 = 0;
        }
        if (i5 &= 4 != 0) {
            obj3 = 1;
        }
        return TransformableKt.transformable(modifier, transformableState2, obj2, obj3);
    }
}
