package com.android.billingclient.api;

/* loaded from: classes.dex */
final class w {

    static final com.android.billingclient.api.g a;
    static final com.android.billingclient.api.g b;
    static final com.android.billingclient.api.g c;
    static final com.android.billingclient.api.g d;
    static final com.android.billingclient.api.g e;
    static final com.android.billingclient.api.g f;
    static final com.android.billingclient.api.g g;
    static final com.android.billingclient.api.g h;
    static final com.android.billingclient.api.g i;
    static final com.android.billingclient.api.g j;
    static final com.android.billingclient.api.g k;
    static final com.android.billingclient.api.g l;
    static final com.android.billingclient.api.g m;
    static final com.android.billingclient.api.g n;
    static final com.android.billingclient.api.g o;
    static final com.android.billingclient.api.g p;
    static final com.android.billingclient.api.g q;
    static {
        com.android.billingclient.api.g.a aVar = g.c();
        int i = 3;
        aVar.c(i);
        aVar.b("Google Play In-app Billing API version is less than 3");
        w.a = aVar.a();
        com.android.billingclient.api.g.a aVar2 = g.c();
        aVar2.c(i);
        aVar2.b("Google Play In-app Billing API version is less than 9");
        w.b = aVar2.a();
        com.android.billingclient.api.g.a aVar3 = g.c();
        aVar3.c(i);
        aVar3.b("Billing service unavailable on device.");
        w.c = aVar3.a();
        com.android.billingclient.api.g.a aVar4 = g.c();
        int i3 = 5;
        aVar4.c(i3);
        aVar4.b("Client is already in the process of connecting to billing service.");
        w.d = aVar4.a();
        com.android.billingclient.api.g.a aVar5 = g.c();
        aVar5.c(i);
        aVar5.b("Play Store version installed does not support cross selling products.");
        aVar5.a();
        com.android.billingclient.api.g.a aVar6 = g.c();
        aVar6.c(i3);
        aVar6.b("The list of SKUs can't be empty.");
        w.e = aVar6.a();
        com.android.billingclient.api.g.a aVar7 = g.c();
        aVar7.c(i3);
        aVar7.b("SKU type can't be empty.");
        w.f = aVar7.a();
        com.android.billingclient.api.g.a aVar8 = g.c();
        int i2 = -2;
        aVar8.c(i2);
        aVar8.b("Client does not support extra params.");
        w.g = aVar8.a();
        com.android.billingclient.api.g.a aVar9 = g.c();
        aVar9.c(i2);
        aVar9.b("Client does not support the feature.");
        w.h = aVar9.a();
        com.android.billingclient.api.g.a aVar10 = g.c();
        aVar10.c(i2);
        aVar10.b("Client does not support get purchase history.");
        w.i = aVar10.a();
        com.android.billingclient.api.g.a aVar11 = g.c();
        aVar11.c(i3);
        aVar11.b("Invalid purchase token.");
        w.j = aVar11.a();
        com.android.billingclient.api.g.a aVar12 = g.c();
        aVar12.c(6);
        aVar12.b("An internal error occurred.");
        w.k = aVar12.a();
        com.android.billingclient.api.g.a aVar13 = g.c();
        aVar13.c(4);
        aVar13.b("Item is unavailable for purchase.");
        aVar13.a();
        com.android.billingclient.api.g.a aVar14 = g.c();
        aVar14.c(i3);
        aVar14.b("SKU can't be null.");
        aVar14.a();
        com.android.billingclient.api.g.a aVar15 = g.c();
        aVar15.c(i3);
        aVar15.b("SKU type can't be null.");
        aVar15.a();
        com.android.billingclient.api.g.a aVar16 = g.c();
        aVar16.c(0);
        w.l = aVar16.a();
        com.android.billingclient.api.g.a aVar17 = g.c();
        aVar17.c(-1);
        aVar17.b("Service connection is disconnected.");
        w.m = aVar17.a();
        com.android.billingclient.api.g.a aVar18 = g.c();
        aVar18.c(-3);
        aVar18.b("Timeout communicating with service.");
        w.n = aVar18.a();
        com.android.billingclient.api.g.a aVar19 = g.c();
        aVar19.c(i2);
        aVar19.b("Client doesn't support subscriptions.");
        w.o = aVar19.a();
        com.android.billingclient.api.g.a aVar20 = g.c();
        aVar20.c(i2);
        aVar20.b("Client doesn't support subscriptions update.");
        aVar20.a();
        com.android.billingclient.api.g.a aVar21 = g.c();
        aVar21.c(i2);
        aVar21.b("Client doesn't support multi-item purchases.");
        w.p = aVar21.a();
        com.android.billingclient.api.g.a aVar22 = g.c();
        aVar22.c(i3);
        aVar22.b("Unknown feature");
        w.q = aVar22.a();
    }
}
