package app.dogo.com.dogo_android.j;

import kotlin.Metadata;
import kotlin.d0.c.l;
import kotlin.d0.d.c0;
import kotlin.d0.d.n;
import kotlin.w;
import m.a.c.e.d;
import m.a.c.k.c;
import m.a.c.k.c.a;

/* compiled from: viewModelModule.kt */
@Metadata(d1 = "\u0000\n\n\u0000\n\u0002\u0018\u0002\n\u0002\u0008\u0003\"\u0011\u0010\u0000\u001a\u00020\u0001¢\u0006\u0008\n\u0000\u001a\u0004\u0008\u0002\u0010\u0003¨\u0006\u0004", d2 = {"viewModelModule", "Lorg/koin/core/module/Module;", "getViewModelModule", "()Lorg/koin/core/module/Module;", "app_release"}, k = 2, mv = {1, 5, 1}, xi = 48)
/* loaded from: classes.dex */
public final class g {

    private static final m.a.c.h.a a;

    @Metadata(d1 = "\u0000\n\n\u0000\n\u0002\u0010\u0002\n\u0002\u0018\u0002\u0010\u0000\u001a\u00020\u0001*\u00020\u0002H\n", d2 = {"<anonymous>", "", "Lorg/koin/core/module/Module;"}, k = 3, mv = {1, 5, 1}, xi = 48)
    static final class a extends kotlin.d0.d.p implements l<m.a.c.h.a, w> {

        public static final g.a a = new g$a();
        @Override // kotlin.d0.d.p
        public final void a(m.a.c.h.a aVar) {
            n.f(aVar, "$this$module");
            c.a aVar3 = ScopeRegistry.e;
            m.a.c.j.c cVar4 = aVar3.a();
            d factory2 = Kind.Factory;
            BeanDefinition beanDefinition4 = new BeanDefinition(cVar4, c0.b(SplashScreenViewModel.class), null, app.dogo.com.dogo_android.di.g.a.m.a, factory2, p.g());
            m.a.c.j.a aVar107 = null;
            int i402 = 0;
            Module.f(aVar, str, new FactoryInstanceFactory(beanDefinition4), false, 4, i402);
            m.a.c.j.c cVar5 = aVar3.a();
            m.a.c.j.a aVar109 = null;
            BeanDefinition beanDefinition5 = new BeanDefinition(cVar5, c0.b(ClickerSelectViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.x.a, factory2, p.g());
            Module.f(aVar, str2, new FactoryInstanceFactory(beanDefinition5), false, 4, i402);
            m.a.c.j.c cVar6 = aVar3.a();
            BeanDefinition beanDefinition6 = new BeanDefinition(cVar6, c0.b(SessionViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.i0.a, factory2, p.g());
            Module.f(aVar, str3, new FactoryInstanceFactory(beanDefinition6), false, 4, i402);
            m.a.c.j.c cVar7 = aVar3.a();
            BeanDefinition beanDefinition7 = new BeanDefinition(cVar7, c0.b(ClickerViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.t0.a, factory2, p.g());
            Module.f(aVar, str4, new FactoryInstanceFactory(beanDefinition7), false, 4, i402);
            m.a.c.j.c cVar8 = aVar3.a();
            BeanDefinition beanDefinition8 = new BeanDefinition(cVar8, c0.b(GoodExampleVideoViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.e1.a, factory2, p.g());
            Module.f(aVar, str5, new FactoryInstanceFactory(beanDefinition8), false, 4, i402);
            m.a.c.j.c cVar9 = aVar3.a();
            BeanDefinition beanDefinition9 = new BeanDefinition(cVar9, c0.b(LanguageSelectViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.p1.a, factory2, p.g());
            Module.f(aVar, str6, new FactoryInstanceFactory(beanDefinition9), false, 4, i402);
            m.a.c.j.c cVar10 = aVar3.a();
            BeanDefinition beanDefinition10 = new BeanDefinition(cVar10, c0.b(ProgramLessonsListViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.a2.a, factory2, p.g());
            Module.f(aVar, str7, new FactoryInstanceFactory(beanDefinition10), false, 4, i402);
            m.a.c.j.c cVar11 = aVar3.a();
            BeanDefinition beanDefinition11 = new BeanDefinition(cVar11, c0.b(ChallengeNotificationCenterViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.l2.a, factory2, p.g());
            Module.f(aVar, str8, new FactoryInstanceFactory(beanDefinition11), false, 4, i402);
            m.a.c.j.c cVar12 = aVar3.a();
            BeanDefinition beanDefinition12 = new BeanDefinition(cVar12, c0.b(ProgramLessonViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.w2.a, factory2, p.g());
            Module.f(aVar, str9, new FactoryInstanceFactory(beanDefinition12), false, 4, i402);
            m.a.c.j.c cVar13 = aVar3.a();
            BeanDefinition beanDefinition13 = new BeanDefinition(cVar13, c0.b(ProgramLessonCompleteViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.c.a, factory2, p.g());
            Module.f(aVar, str10, new FactoryInstanceFactory(beanDefinition13), false, 4, i402);
            m.a.c.j.c cVar14 = aVar3.a();
            BeanDefinition beanDefinition14 = new BeanDefinition(cVar14, c0.b(ProgramTasksListViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.d.a, factory2, p.g());
            Module.f(aVar, str11, new FactoryInstanceFactory(beanDefinition14), false, 4, i402);
            m.a.c.j.c cVar15 = aVar3.a();
            BeanDefinition beanDefinition15 = new BeanDefinition(cVar15, c0.b(DogSelectViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.e.a, factory2, p.g());
            Module.f(aVar, str12, new FactoryInstanceFactory(beanDefinition15), false, 4, i402);
            m.a.c.j.c cVar16 = aVar3.a();
            BeanDefinition beanDefinition16 = new BeanDefinition(cVar16, c0.b(MainScreenViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.f.a, factory2, p.g());
            Module.f(aVar, str13, new FactoryInstanceFactory(beanDefinition16), false, 4, i402);
            m.a.c.j.c cVar17 = aVar3.a();
            BeanDefinition beanDefinition17 = new BeanDefinition(cVar17, c0.b(ProgramTrainingPlanViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.g.a, factory2, p.g());
            Module.f(aVar, str14, new FactoryInstanceFactory(beanDefinition17), false, 4, i402);
            m.a.c.j.c cVar18 = aVar3.a();
            BeanDefinition beanDefinition18 = new BeanDefinition(cVar18, c0.b(ProgramQuestionViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.h.a, factory2, p.g());
            Module.f(aVar, str15, new FactoryInstanceFactory(beanDefinition18), false, 4, i402);
            m.a.c.j.c cVar19 = aVar3.a();
            BeanDefinition beanDefinition19 = new BeanDefinition(cVar19, c0.b(ProgramQuestionCorrectAnswerViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.i.a, factory2, p.g());
            Module.f(aVar, str16, new FactoryInstanceFactory(beanDefinition19), false, 4, i402);
            m.a.c.j.c cVar20 = aVar3.a();
            BeanDefinition beanDefinition20 = new BeanDefinition(cVar20, c0.b(ProgramListViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.j.a, factory2, p.g());
            Module.f(aVar, str17, new FactoryInstanceFactory(beanDefinition20), false, 4, i402);
            m.a.c.j.c cVar21 = aVar3.a();
            BeanDefinition beanDefinition21 = new BeanDefinition(cVar21, c0.b(DebugDataFragmentViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.k.a, factory2, p.g());
            Module.f(aVar, str18, new FactoryInstanceFactory(beanDefinition21), false, 4, i402);
            m.a.c.j.c cVar22 = aVar3.a();
            BeanDefinition beanDefinition22 = new BeanDefinition(cVar22, c0.b(InstagramInviteViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.l.a, factory2, p.g());
            Module.f(aVar, str19, new FactoryInstanceFactory(beanDefinition22), false, 4, i402);
            m.a.c.j.c cVar23 = aVar3.a();
            BeanDefinition beanDefinition23 = new BeanDefinition(cVar23, c0.b(TiktokInviteViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.n.a, factory2, p.g());
            Module.f(aVar, str20, new FactoryInstanceFactory(beanDefinition23), false, 4, i402);
            m.a.c.j.c cVar24 = aVar3.a();
            BeanDefinition beanDefinition24 = new BeanDefinition(cVar24, c0.b(SubscriptionViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.o.a, factory2, p.g());
            Module.f(aVar, str21, new FactoryInstanceFactory(beanDefinition24), false, 4, i402);
            m.a.c.j.c cVar25 = aVar3.a();
            BeanDefinition beanDefinition25 = new BeanDefinition(cVar25, c0.b(LessonExamListViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.p.a, factory2, p.g());
            Module.f(aVar, str22, new FactoryInstanceFactory(beanDefinition25), false, 4, i402);
            m.a.c.j.c cVar26 = aVar3.a();
            BeanDefinition beanDefinition26 = new BeanDefinition(cVar26, c0.b(DebugFeatureEnablerViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.q.a, factory2, p.g());
            Module.f(aVar, str23, new FactoryInstanceFactory(beanDefinition26), false, 4, i402);
            m.a.c.j.c cVar27 = aVar3.a();
            BeanDefinition beanDefinition27 = new BeanDefinition(cVar27, c0.b(ProgramLessonExamUnlockedViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.r.a, factory2, p.g());
            Module.f(aVar, str24, new FactoryInstanceFactory(beanDefinition27), false, 4, i402);
            m.a.c.j.c cVar28 = aVar3.a();
            BeanDefinition beanDefinition28 = new BeanDefinition(cVar28, c0.b(OnboardingSurveyViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.s.a, factory2, p.g());
            Module.f(aVar, str25, new FactoryInstanceFactory(beanDefinition28), false, 4, i402);
            m.a.c.j.c cVar29 = aVar3.a();
            BeanDefinition beanDefinition29 = new BeanDefinition(cVar29, c0.b(OnboardingProgramGenerationViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.t.a, factory2, p.g());
            Module.f(aVar, str26, new FactoryInstanceFactory(beanDefinition29), false, 4, i402);
            m.a.c.j.c cVar30 = aVar3.a();
            BeanDefinition beanDefinition30 = new BeanDefinition(cVar30, c0.b(DashboardProgramGenerationViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.u.a, factory2, p.g());
            Module.f(aVar, str27, new FactoryInstanceFactory(beanDefinition30), false, 4, i402);
            m.a.c.j.c cVar31 = aVar3.a();
            BeanDefinition beanDefinition31 = new BeanDefinition(cVar31, c0.b(OnboardingStartViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.v.a, factory2, p.g());
            Module.f(aVar, str28, new FactoryInstanceFactory(beanDefinition31), false, 4, i402);
            m.a.c.j.c cVar32 = aVar3.a();
            BeanDefinition beanDefinition32 = new BeanDefinition(cVar32, c0.b(OnboardingSharedViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.w.a, factory2, p.g());
            Module.f(aVar, str29, new FactoryInstanceFactory(beanDefinition32), false, 4, i402);
            m.a.c.j.c cVar33 = aVar3.a();
            BeanDefinition beanDefinition33 = new BeanDefinition(cVar33, c0.b(OnboardingNameViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.y.a, factory2, p.g());
            Module.f(aVar, str30, new FactoryInstanceFactory(beanDefinition33), false, 4, i402);
            m.a.c.j.c cVar34 = aVar3.a();
            BeanDefinition beanDefinition34 = new BeanDefinition(cVar34, c0.b(ChallengeCommentsViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.z.a, factory2, p.g());
            Module.f(aVar, str31, new FactoryInstanceFactory(beanDefinition34), false, 4, i402);
            m.a.c.j.c cVar35 = aVar3.a();
            BeanDefinition beanDefinition35 = new BeanDefinition(cVar35, c0.b(SettingsViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.a0.a, factory2, p.g());
            Module.f(aVar, str32, new FactoryInstanceFactory(beanDefinition35), false, 4, i402);
            m.a.c.j.c cVar36 = aVar3.a();
            BeanDefinition beanDefinition36 = new BeanDefinition(cVar36, c0.b(LessonIntroductionViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.b0.a, factory2, p.g());
            Module.f(aVar, str33, new FactoryInstanceFactory(beanDefinition36), false, 4, i402);
            m.a.c.j.c cVar37 = aVar3.a();
            BeanDefinition beanDefinition37 = new BeanDefinition(cVar37, c0.b(ChallengeShareViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.c0.a, factory2, p.g());
            Module.f(aVar, str34, new FactoryInstanceFactory(beanDefinition37), false, 4, i402);
            m.a.c.j.c cVar38 = aVar3.a();
            BeanDefinition beanDefinition38 = new BeanDefinition(cVar38, c0.b(UserInformationViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.d0.a, factory2, p.g());
            Module.f(aVar, str35, new FactoryInstanceFactory(beanDefinition38), false, 4, i402);
            m.a.c.j.c cVar39 = aVar3.a();
            BeanDefinition beanDefinition39 = new BeanDefinition(cVar39, c0.b(ReminderIntervalViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.e0.a, factory2, p.g());
            Module.f(aVar, str36, new FactoryInstanceFactory(beanDefinition39), false, 4, i402);
            m.a.c.j.c cVar40 = aVar3.a();
            BeanDefinition beanDefinition40 = new BeanDefinition(cVar40, c0.b(FaqListViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.f0.a, factory2, p.g());
            Module.f(aVar, str37, new FactoryInstanceFactory(beanDefinition40), false, 4, i402);
            m.a.c.j.c cVar41 = aVar3.a();
            BeanDefinition beanDefinition41 = new BeanDefinition(cVar41, c0.b(RedeemCodeViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.g0.a, factory2, p.g());
            Module.f(aVar, str38, new FactoryInstanceFactory(beanDefinition41), false, 4, i402);
            m.a.c.j.c cVar42 = aVar3.a();
            BeanDefinition beanDefinition42 = new BeanDefinition(cVar42, c0.b(LessonExamHistoryViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.h0.a, factory2, p.g());
            Module.f(aVar, str39, new FactoryInstanceFactory(beanDefinition42), false, 4, i402);
            m.a.c.j.c cVar43 = aVar3.a();
            BeanDefinition beanDefinition43 = new BeanDefinition(cVar43, c0.b(LegacySubscriptionSharedViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.j0.a, factory2, p.g());
            Module.f(aVar, str40, new FactoryInstanceFactory(beanDefinition43), false, 4, i402);
            m.a.c.j.c cVar44 = aVar3.a();
            BeanDefinition beanDefinition44 = new BeanDefinition(cVar44, c0.b(OnboardingPagerViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.k0.a, factory2, p.g());
            Module.f(aVar, str41, new FactoryInstanceFactory(beanDefinition44), false, 4, i402);
            m.a.c.j.c cVar45 = aVar3.a();
            BeanDefinition beanDefinition45 = new BeanDefinition(cVar45, c0.b(NewsletterBenefitsViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.l0.a, factory2, p.g());
            Module.f(aVar, str42, new FactoryInstanceFactory(beanDefinition45), false, 4, i402);
            m.a.c.j.c cVar46 = aVar3.a();
            BeanDefinition beanDefinition46 = new BeanDefinition(cVar46, c0.b(SharePromptViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.m0.a, factory2, p.g());
            Module.f(aVar, str43, new FactoryInstanceFactory(beanDefinition46), false, 4, i402);
            m.a.c.j.c cVar47 = aVar3.a();
            BeanDefinition beanDefinition47 = new BeanDefinition(cVar47, c0.b(TrainingReminderViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.n0.a, factory2, p.g());
            Module.f(aVar, str44, new FactoryInstanceFactory(beanDefinition47), false, 4, i402);
            m.a.c.j.c cVar48 = aVar3.a();
            BeanDefinition beanDefinition48 = new BeanDefinition(cVar48, c0.b(ClickerIntroductionViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.o0.a, factory2, p.g());
            Module.f(aVar, str45, new FactoryInstanceFactory(beanDefinition48), false, 4, i402);
            m.a.c.j.c cVar49 = aVar3.a();
            BeanDefinition beanDefinition49 = new BeanDefinition(cVar49, c0.b(LibraryViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.p0.a, factory2, p.g());
            Module.f(aVar, str46, new FactoryInstanceFactory(beanDefinition49), false, 4, i402);
            m.a.c.j.c cVar50 = aVar3.a();
            BeanDefinition beanDefinition50 = new BeanDefinition(cVar50, c0.b(ArticleDetailsViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.q0.a, factory2, p.g());
            Module.f(aVar, str47, new FactoryInstanceFactory(beanDefinition50), false, 4, i402);
            m.a.c.j.c cVar51 = aVar3.a();
            BeanDefinition beanDefinition51 = new BeanDefinition(cVar51, c0.b(ArticleListViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.r0.a, factory2, p.g());
            Module.f(aVar, str48, new FactoryInstanceFactory(beanDefinition51), false, 4, i402);
            m.a.c.j.c cVar = aVar3.a();
            BeanDefinition beanDefinition = new BeanDefinition(cVar, c0.b(TrickListViewModel.class), aVar109, app.dogo.com.dogo_android.di.g.a.s0.a, factory2, p.g());
            Module.f(aVar, org.koin.core.definition.b.a(beanDefinition.b(), aVar107, cVar), new FactoryInstanceFactory(beanDefinition), false, 4, null);
            c.a aVar4 = ScopeRegistry.e;
            m.a.c.j.c cVar52 = aVar4.a();
            d factory22 = Kind.Factory;
            m.a.c.j.a aVar108 = null;
            BeanDefinition beanDefinition52 = new BeanDefinition(cVar52, c0.b(RateTrickViewModel2.class), aVar108, app.dogo.com.dogo_android.di.g.a.u0.a, factory22, p.g());
            int i403 = 0;
            Module.f(aVar, str49, new FactoryInstanceFactory(beanDefinition52), false, 4, i403);
            m.a.c.j.c cVar53 = aVar4.a();
            m.a.c.j.a aVar110 = null;
            BeanDefinition beanDefinition53 = new BeanDefinition(cVar53, c0.b(RecordVideoViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.v0.a, factory22, p.g());
            Module.f(aVar, str50, new FactoryInstanceFactory(beanDefinition53), false, 4, i403);
            m.a.c.j.c cVar54 = aVar4.a();
            BeanDefinition beanDefinition54 = new BeanDefinition(cVar54, c0.b(LoginViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.w0.a, factory22, p.g());
            Module.f(aVar, str51, new FactoryInstanceFactory(beanDefinition54), false, 4, i403);
            m.a.c.j.c cVar55 = aVar4.a();
            BeanDefinition beanDefinition55 = new BeanDefinition(cVar55, c0.b(DashboardViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.x0.a, factory22, p.g());
            Module.f(aVar, str52, new FactoryInstanceFactory(beanDefinition55), false, 4, i403);
            m.a.c.j.c cVar56 = aVar4.a();
            BeanDefinition beanDefinition56 = new BeanDefinition(cVar56, c0.b(InAppOneTenViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.y0.a, factory22, p.g());
            Module.f(aVar, str53, new FactoryInstanceFactory(beanDefinition56), false, 4, i403);
            m.a.c.j.c cVar57 = aVar4.a();
            BeanDefinition beanDefinition57 = new BeanDefinition(cVar57, c0.b(InAppFeedbackViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.z0.a, factory22, p.g());
            Module.f(aVar, str54, new FactoryInstanceFactory(beanDefinition57), false, 4, i403);
            m.a.c.j.c cVar58 = aVar4.a();
            BeanDefinition beanDefinition58 = new BeanDefinition(cVar58, c0.b(CertificateDetailViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.a1.a, factory22, p.g());
            Module.f(aVar, str55, new FactoryInstanceFactory(beanDefinition58), false, 4, i403);
            m.a.c.j.c cVar59 = aVar4.a();
            BeanDefinition beanDefinition59 = new BeanDefinition(cVar59, c0.b(PottyProgramReminderViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.b1.a, factory22, p.g());
            Module.f(aVar, str56, new FactoryInstanceFactory(beanDefinition59), false, 4, i403);
            m.a.c.j.c cVar60 = aVar4.a();
            BeanDefinition beanDefinition60 = new BeanDefinition(cVar60, c0.b(DogPreviewViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.c1.a, factory22, p.g());
            Module.f(aVar, str57, new FactoryInstanceFactory(beanDefinition60), false, 4, i403);
            m.a.c.j.c cVar61 = aVar4.a();
            BeanDefinition beanDefinition61 = new BeanDefinition(cVar61, c0.b(DogPreviewNameViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.d1.a, factory22, p.g());
            Module.f(aVar, str58, new FactoryInstanceFactory(beanDefinition61), false, 4, i403);
            m.a.c.j.c cVar62 = aVar4.a();
            BeanDefinition beanDefinition62 = new BeanDefinition(cVar62, c0.b(DogPreviewBreedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.f1.a, factory22, p.g());
            Module.f(aVar, str59, new FactoryInstanceFactory(beanDefinition62), false, 4, i403);
            m.a.c.j.c cVar63 = aVar4.a();
            BeanDefinition beanDefinition63 = new BeanDefinition(cVar63, c0.b(DogPreviewBirthdayViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.g1.a, factory22, p.g());
            Module.f(aVar, str60, new FactoryInstanceFactory(beanDefinition63), false, 4, i403);
            m.a.c.j.c cVar64 = aVar4.a();
            BeanDefinition beanDefinition64 = new BeanDefinition(cVar64, c0.b(DogPreviewGenderViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.h1.a, factory22, p.g());
            Module.f(aVar, str61, new FactoryInstanceFactory(beanDefinition64), false, 4, i403);
            m.a.c.j.c cVar65 = aVar4.a();
            BeanDefinition beanDefinition65 = new BeanDefinition(cVar65, c0.b(RatePromptViewModelV2.class), aVar110, app.dogo.com.dogo_android.di.g.a.i1.a, factory22, p.g());
            Module.f(aVar, str62, new FactoryInstanceFactory(beanDefinition65), false, 4, i403);
            m.a.c.j.c cVar66 = aVar4.a();
            BeanDefinition beanDefinition66 = new BeanDefinition(cVar66, c0.b(ChallengeProfileDialogViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.j1.a, factory22, p.g());
            Module.f(aVar, str63, new FactoryInstanceFactory(beanDefinition66), false, 4, i403);
            m.a.c.j.c cVar67 = aVar4.a();
            BeanDefinition beanDefinition67 = new BeanDefinition(cVar67, c0.b(DailyWorkoutOverviewViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.k1.a, factory22, p.g());
            Module.f(aVar, str64, new FactoryInstanceFactory(beanDefinition67), false, 4, i403);
            m.a.c.j.c cVar68 = aVar4.a();
            BeanDefinition beanDefinition68 = new BeanDefinition(cVar68, c0.b(DailyWorkoutViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.l1.a, factory22, p.g());
            Module.f(aVar, str65, new FactoryInstanceFactory(beanDefinition68), false, 4, i403);
            m.a.c.j.c cVar69 = aVar4.a();
            BeanDefinition beanDefinition69 = new BeanDefinition(cVar69, c0.b(SimpleTrickListViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.m1.a, factory22, p.g());
            Module.f(aVar, str66, new FactoryInstanceFactory(beanDefinition69), false, 4, i403);
            m.a.c.j.c cVar70 = aVar4.a();
            BeanDefinition beanDefinition70 = new BeanDefinition(cVar70, c0.b(DailyWorkoutUnlockedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.n1.a, factory22, p.g());
            Module.f(aVar, str67, new FactoryInstanceFactory(beanDefinition70), false, 4, i403);
            m.a.c.j.c cVar71 = aVar4.a();
            BeanDefinition beanDefinition71 = new BeanDefinition(cVar71, c0.b(DailyWorkoutCompletedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.o1.a, factory22, p.g());
            Module.f(aVar, str68, new FactoryInstanceFactory(beanDefinition71), false, 4, i403);
            m.a.c.j.c cVar72 = aVar4.a();
            BeanDefinition beanDefinition72 = new BeanDefinition(cVar72, c0.b(TrickDetailsViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.q1.a, factory22, p.g());
            Module.f(aVar, str69, new FactoryInstanceFactory(beanDefinition72), false, 4, i403);
            m.a.c.j.c cVar73 = aVar4.a();
            BeanDefinition beanDefinition73 = new BeanDefinition(cVar73, c0.b(TrickBigTimerViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.r1.a, factory22, p.g());
            Module.f(aVar, str70, new FactoryInstanceFactory(beanDefinition73), false, 4, i403);
            m.a.c.j.c cVar74 = aVar4.a();
            BeanDefinition beanDefinition74 = new BeanDefinition(cVar74, c0.b(ChallengeReportViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.s1.a, factory22, p.g());
            Module.f(aVar, str71, new FactoryInstanceFactory(beanDefinition74), false, 4, i403);
            m.a.c.j.c cVar75 = aVar4.a();
            BeanDefinition beanDefinition75 = new BeanDefinition(cVar75, c0.b(DogCreationSharedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.t1.a, factory22, p.g());
            Module.f(aVar, str72, new FactoryInstanceFactory(beanDefinition75), false, 4, i403);
            m.a.c.j.c cVar76 = aVar4.a();
            BeanDefinition beanDefinition76 = new BeanDefinition(cVar76, c0.b(DogCreationAvatarViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.u1.a, factory22, p.g());
            Module.f(aVar, str73, new FactoryInstanceFactory(beanDefinition76), false, 4, i403);
            m.a.c.j.c cVar77 = aVar4.a();
            BeanDefinition beanDefinition77 = new BeanDefinition(cVar77, c0.b(DogCreationNameViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.v1.a, factory22, p.g());
            Module.f(aVar, str74, new FactoryInstanceFactory(beanDefinition77), false, 4, i403);
            m.a.c.j.c cVar78 = aVar4.a();
            BeanDefinition beanDefinition78 = new BeanDefinition(cVar78, c0.b(DogCreationBreedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.w1.a, factory22, p.g());
            Module.f(aVar, str75, new FactoryInstanceFactory(beanDefinition78), false, 4, i403);
            m.a.c.j.c cVar79 = aVar4.a();
            BeanDefinition beanDefinition79 = new BeanDefinition(cVar79, c0.b(DogCreationBreedSearchViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.x1.a, factory22, p.g());
            Module.f(aVar, str76, new FactoryInstanceFactory(beanDefinition79), false, 4, i403);
            m.a.c.j.c cVar80 = aVar4.a();
            BeanDefinition beanDefinition80 = new BeanDefinition(cVar80, c0.b(DogCreationBirthdayViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.y1.a, factory22, p.g());
            Module.f(aVar, str77, new FactoryInstanceFactory(beanDefinition80), false, 4, i403);
            m.a.c.j.c cVar81 = aVar4.a();
            BeanDefinition beanDefinition81 = new BeanDefinition(cVar81, c0.b(DogCreationGenderViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.z1.a, factory22, p.g());
            Module.f(aVar, str78, new FactoryInstanceFactory(beanDefinition81), false, 4, i403);
            m.a.c.j.c cVar82 = aVar4.a();
            BeanDefinition beanDefinition82 = new BeanDefinition(cVar82, c0.b(ChallengeEntryCreationViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.b2.a, factory22, p.g());
            Module.f(aVar, str79, new FactoryInstanceFactory(beanDefinition82), false, 4, i403);
            m.a.c.j.c cVar83 = aVar4.a();
            BeanDefinition beanDefinition83 = new BeanDefinition(cVar83, c0.b(ChallengeDetailsViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.c2.a, factory22, p.g());
            Module.f(aVar, str80, new FactoryInstanceFactory(beanDefinition83), false, 4, i403);
            m.a.c.j.c cVar84 = aVar4.a();
            BeanDefinition beanDefinition84 = new BeanDefinition(cVar84, c0.b(DogParentsViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.d2.a, factory22, p.g());
            Module.f(aVar, str81, new FactoryInstanceFactory(beanDefinition84), false, 4, i403);
            m.a.c.j.c cVar85 = aVar4.a();
            BeanDefinition beanDefinition85 = new BeanDefinition(cVar85, c0.b(DogInviteAcceptanceSharedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.e2.a, factory22, p.g());
            Module.f(aVar, str82, new FactoryInstanceFactory(beanDefinition85), false, 4, i403);
            m.a.c.j.c cVar86 = aVar4.a();
            BeanDefinition beanDefinition86 = new BeanDefinition(cVar86, c0.b(ProgramOverviewViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.f2.a, factory22, p.g());
            Module.f(aVar, str83, new FactoryInstanceFactory(beanDefinition86), false, 4, i403);
            m.a.c.j.c cVar87 = aVar4.a();
            BeanDefinition beanDefinition87 = new BeanDefinition(cVar87, c0.b(DogLogEditViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.g2.a, factory22, p.g());
            Module.f(aVar, str84, new FactoryInstanceFactory(beanDefinition87), false, 4, i403);
            m.a.c.j.c cVar88 = aVar4.a();
            BeanDefinition beanDefinition88 = new BeanDefinition(cVar88, c0.b(DogLogCalendarViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.h2.a, factory22, p.g());
            Module.f(aVar, str85, new FactoryInstanceFactory(beanDefinition88), false, 4, i403);
            m.a.c.j.c cVar89 = aVar4.a();
            BeanDefinition beanDefinition89 = new BeanDefinition(cVar89, c0.b(DogLogSelectViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.i2.a, factory22, p.g());
            Module.f(aVar, str86, new FactoryInstanceFactory(beanDefinition89), false, 4, i403);
            m.a.c.j.c cVar90 = aVar4.a();
            BeanDefinition beanDefinition90 = new BeanDefinition(cVar90, c0.b(PottyProgramOverviewViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.j2.a, factory22, p.g());
            Module.f(aVar, str87, new FactoryInstanceFactory(beanDefinition90), false, 4, i403);
            m.a.c.j.c cVar91 = aVar4.a();
            BeanDefinition beanDefinition91 = new BeanDefinition(cVar91, c0.b(PottyTrackerOverviewViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.k2.a, factory22, p.g());
            Module.f(aVar, str88, new FactoryInstanceFactory(beanDefinition91), false, 4, i403);
            m.a.c.j.c cVar92 = aVar4.a();
            BeanDefinition beanDefinition92 = new BeanDefinition(cVar92, c0.b(BitingProgramOverviewViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.m2.a, factory22, p.g());
            Module.f(aVar, str89, new FactoryInstanceFactory(beanDefinition92), false, 4, i403);
            m.a.c.j.c cVar93 = aVar4.a();
            BeanDefinition beanDefinition93 = new BeanDefinition(cVar93, c0.b(VariationTipsViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.n2.a, factory22, p.g());
            Module.f(aVar, str90, new FactoryInstanceFactory(beanDefinition93), false, 4, i403);
            m.a.c.j.c cVar94 = aVar4.a();
            BeanDefinition beanDefinition94 = new BeanDefinition(cVar94, c0.b(VariationsUnlockedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.o2.a, factory22, p.g());
            Module.f(aVar, str91, new FactoryInstanceFactory(beanDefinition94), false, 4, i403);
            m.a.c.j.c cVar95 = aVar4.a();
            BeanDefinition beanDefinition95 = new BeanDefinition(cVar95, c0.b(SpecialProgramCertificateViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.p2.a, factory22, p.g());
            Module.f(aVar, str92, new FactoryInstanceFactory(beanDefinition95), false, 4, i403);
            m.a.c.j.c cVar96 = aVar4.a();
            BeanDefinition beanDefinition96 = new BeanDefinition(cVar96, c0.b(ProgramTrickTryViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.q2.a, factory22, p.g());
            Module.f(aVar, str93, new FactoryInstanceFactory(beanDefinition96), false, 4, i403);
            m.a.c.j.c cVar97 = aVar4.a();
            BeanDefinition beanDefinition97 = new BeanDefinition(cVar97, c0.b(JsonArrayEditViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.r2.a, factory22, p.g());
            Module.f(aVar, str94, new FactoryInstanceFactory(beanDefinition97), false, 4, i403);
            m.a.c.j.c cVar98 = aVar4.a();
            BeanDefinition beanDefinition98 = new BeanDefinition(cVar98, c0.b(FirstExamUnlockedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.s2.a, factory22, p.g());
            Module.f(aVar, str95, new FactoryInstanceFactory(beanDefinition98), false, 4, i403);
            m.a.c.j.c cVar99 = aVar4.a();
            BeanDefinition beanDefinition99 = new BeanDefinition(cVar99, c0.b(GoalNotAchievedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.t2.a, factory22, p.g());
            Module.f(aVar, str96, new FactoryInstanceFactory(beanDefinition99), false, 4, i403);
            m.a.c.j.c cVar2 = aVar4.a();
            BeanDefinition beanDefinition2 = new BeanDefinition(cVar2, c0.b(TrainingMetricsStreakCompletedViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.u2.a, factory22, p.g());
            Module.f(aVar, org.koin.core.definition.b.a(beanDefinition2.b(), aVar107, cVar2), new FactoryInstanceFactory(beanDefinition2), false, 4, null);
            c.a aVar5 = ScopeRegistry.e;
            m.a.c.j.c cVar100 = aVar5.a();
            d factory23 = Kind.Factory;
            BeanDefinition beanDefinition100 = new BeanDefinition(cVar100, c0.b(ExamRecordViewModel.class), aVar108, app.dogo.com.dogo_android.di.g.a.v2.a, factory23, p.g());
            int i404 = 0;
            Module.f(aVar, str97, new FactoryInstanceFactory(beanDefinition100), false, 4, i404);
            m.a.c.j.c cVar101 = aVar5.a();
            BeanDefinition beanDefinition101 = new BeanDefinition(cVar101, c0.b(ExamPlaybackViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.a.a, factory23, p.g());
            Module.f(aVar, str98, new FactoryInstanceFactory(beanDefinition101), false, 4, i404);
            m.a.c.j.c cVar3 = aVar5.a();
            BeanDefinition beanDefinition3 = new BeanDefinition(cVar3, c0.b(ExamFlowViewModel.class), aVar110, app.dogo.com.dogo_android.di.g.a.b.a, factory23, p.g());
            Module.f(aVar, org.koin.core.definition.b.a(beanDefinition3.b(), aVar107, cVar3), new FactoryInstanceFactory(beanDefinition3), false, 4, null);
        }


        a() {
            super(1);
        }
    }
    static {
        app.dogo.com.dogo_android.di.g.a = b.b(false, app.dogo.com.dogo_android.di.g.a.a, 1, null);
    }

    public static final m.a.c.h.a a() {
        return app.dogo.com.dogo_android.di.g.a;
    }
}
