package io.github.skylot.android.smallapp;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class color {
        public static final int black = 0x7f010000;
        public static final int white = 0x7f010001;
    }

    public static final class drawable {
        public static final int ic_launcher_background = 0x7f020000;
        public static final int ic_launcher_foreground = 0x7f020001;
    }

    public static final class id {
        public static final int text = 0x7f030000;
    }

    /* loaded from: classes.dex */
    public abstract class layout {
        public static int activity_main = 0x7f040000;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f050000;
    }

    public static final class string {
        public static final int app_name = 0x7f060000;
        public static final int hello_android = 0x7f060001;
    }
}
