package com.google.android.gms.measurement.internal;

import android.content.Context;
import com.google.android.gms.internal.measurement.c6;
import com.google.android.gms.internal.measurement.m6;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;

/* loaded from: classes2.dex */
public final class c3 {

    public static final com.google.android.gms.measurement.internal.b3<Long> A;
    public static final com.google.android.gms.measurement.internal.b3<Long> B;
    public static final com.google.android.gms.measurement.internal.b3<Integer> C;
    public static final com.google.android.gms.measurement.internal.b3<Long> D;
    public static final com.google.android.gms.measurement.internal.b3<Integer> E;
    public static final com.google.android.gms.measurement.internal.b3<Integer> F;
    public static final com.google.android.gms.measurement.internal.b3<Integer> G;
    public static final com.google.android.gms.measurement.internal.b3<Integer> H;
    public static final com.google.android.gms.measurement.internal.b3<Integer> I;
    public static final com.google.android.gms.measurement.internal.b3<Long> J;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> K;
    public static final com.google.android.gms.measurement.internal.b3<String> L;
    public static final com.google.android.gms.measurement.internal.b3<Long> M;
    public static final com.google.android.gms.measurement.internal.b3<Integer> N;
    public static final com.google.android.gms.measurement.internal.b3<Double> O;
    public static final com.google.android.gms.measurement.internal.b3<Integer> P;
    public static final com.google.android.gms.measurement.internal.b3<Integer> Q;
    public static final com.google.android.gms.measurement.internal.b3<Long> R;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> S;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> T;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> U;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> V;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> W;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> X;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> Y;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> Z;
    private static final List<com.google.android.gms.measurement.internal.b3<?>> a;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> a0;
    public static final com.google.android.gms.measurement.internal.b3<Long> b;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> b0;
    public static final com.google.android.gms.measurement.internal.b3<Long> c;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> c0;
    public static final com.google.android.gms.measurement.internal.b3<Long> d;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> d0;
    public static final com.google.android.gms.measurement.internal.b3<String> e;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> e0;
    public static final com.google.android.gms.measurement.internal.b3<String> f;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> f0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> g;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> g0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> h;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> h0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> i;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> i0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> j;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> j0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> k;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> k0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> l;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> l0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> m;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> m0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> n;
    public static final com.google.android.gms.measurement.internal.b3<Integer> n0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> o;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> o0;
    public static final com.google.android.gms.measurement.internal.b3<Integer> p;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> p0;
    public static final com.google.android.gms.measurement.internal.b3<String> q;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> q0;
    public static final com.google.android.gms.measurement.internal.b3<Long> r;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> r0;
    public static final com.google.android.gms.measurement.internal.b3<Long> s;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> s0;
    public static final com.google.android.gms.measurement.internal.b3<Long> t;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> t0;
    public static final com.google.android.gms.measurement.internal.b3<Long> u;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> u0;
    public static final com.google.android.gms.measurement.internal.b3<Long> v;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> v0;
    public static final com.google.android.gms.measurement.internal.b3<Long> w;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> w0;
    public static final com.google.android.gms.measurement.internal.b3<Long> x;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> x0;
    public static final com.google.android.gms.measurement.internal.b3<Long> y;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> y0;
    public static final com.google.android.gms.measurement.internal.b3<Long> z;
    public static final com.google.android.gms.measurement.internal.b3<Boolean> z0;
    static {
        ArrayList arrayList = new ArrayList();
        c3.a = Collections.synchronizedList(arrayList);
        HashSet hashSet = new HashSet();
        Collections.synchronizedSet(hashSet);
        Long valueOf = Long.valueOf(10000);
        String str = "measurement.ad_id_cache_time";
        c3.b = c3.a(str, valueOf, valueOf, w.a);
        Long valueOf6 = Long.valueOf(86400000);
        String str12 = "measurement.monitoring.sample_period_millis";
        c3.c = c3.a(str12, valueOf6, valueOf6, i0.a);
        Long valueOf15 = Long.valueOf(3600000);
        c3.d = c3.a("measurement.config.cache_time", valueOf6, valueOf15, z.a);
        String str59 = "https";
        c3.e = c3.a("measurement.config.url_scheme", str59, str59, m0.a);
        String str60 = "app-measurement.com";
        c3.f = c3.a("measurement.config.url_authority", str60, str60, y0.a);
        Integer valueOf22 = 100;
        c3.g = c3.a("measurement.upload.max_bundles", valueOf22, valueOf22, l1.a);
        Integer valueOf23 = 65536;
        c3.h = c3.a("measurement.upload.max_batch_size", valueOf23, valueOf23, x1.a);
        c3.i = c3.a("measurement.upload.max_bundle_size", valueOf23, valueOf23, k2.a);
        Integer valueOf24 = 1000;
        c3.j = c3.a("measurement.upload.max_events_per_bundle", valueOf24, valueOf24, t2.a);
        Integer valueOf29 = 100000;
        c3.k = c3.a("measurement.upload.max_events_per_day", valueOf29, valueOf29, u2.a);
        c3.l = c3.a("measurement.upload.max_error_events_per_day", valueOf24, valueOf24, t0.a);
        Integer valueOf25 = 50000;
        c3.m = c3.a("measurement.upload.max_public_events_per_day", valueOf25, valueOf25, f1.a);
        Integer valueOf26 = 10000;
        c3.n = c3.a("measurement.upload.max_conversions_per_day", valueOf26, valueOf26, q1.a);
        Integer valueOf27 = 10;
        c3.o = c3.a("measurement.upload.max_realtime_events_per_day", valueOf27, valueOf27, b2.a);
        c3.p = c3.a("measurement.store.max_stored_events_per_app", valueOf29, valueOf29, n2.a);
        String str62 = "measurement.upload.url";
        String str74 = "https://app-measurement.com/a";
        c3.q = c3.a(str62, str74, str74, v2.a);
        Long valueOf28 = Long.valueOf(43200000);
        c3.r = c3.a("measurement.upload.backoff_period", valueOf28, valueOf28, w2.a);
        c3.s = c3.a("measurement.upload.window_interval", valueOf15, valueOf15, x2.a);
        String str64 = "measurement.upload.interval";
        c3.t = c3.a(str64, valueOf15, valueOf15, x.a);
        c3.u = c3.a("measurement.upload.realtime_upload_interval", valueOf, valueOf, y.a);
        Long valueOf2 = Long.valueOf(1000);
        c3.v = c3.a("measurement.upload.debug_upload_interval", valueOf2, valueOf2, a0.a);
        Long valueOf3 = Long.valueOf(500);
        c3.w = c3.a("measurement.upload.minimum_delay", valueOf3, valueOf3, c0.a);
        Long valueOf4 = Long.valueOf(60000);
        c3.x = c3.a("measurement.alarm_manager.minimum_interval", valueOf4, valueOf4, d0.a);
        c3.y = c3.a("measurement.upload.stale_data_deletion_interval", valueOf6, valueOf6, e0.a);
        Long valueOf5 = Long.valueOf(604800000);
        String str3 = "measurement.upload.refresh_blacklisted_config_interval";
        c3.z = c3.a(str3, valueOf5, valueOf5, f0.a);
        Long valueOf7 = Long.valueOf(15000);
        com.google.android.gms.measurement.internal.g0 g0Var = g0.a;
        c3.A = c3.a("measurement.upload.initial_upload_delay_time", valueOf7, valueOf7, g0Var);
        Long valueOf8 = Long.valueOf(1800000);
        c3.B = c3.a("measurement.upload.retry_time", valueOf8, valueOf8, h0.a);
        Integer valueOf9 = 6;
        com.google.android.gms.measurement.internal.j0 j0Var = j0.a;
        c3.C = c3.a("measurement.upload.retry_count", valueOf9, valueOf9, j0Var);
        Long valueOf10 = Long.valueOf(2419200000L);
        c3.D = c3.a("measurement.upload.max_queue_time", valueOf10, valueOf10, k0.a);
        Integer valueOf11 = 4;
        c3.E = c3.a("measurement.lifetimevalue.max_currency_tracked", valueOf11, valueOf11, l0.a);
        Integer valueOf12 = 200;
        c3.F = c3.a("measurement.audience.filter_result_max_count", valueOf12, valueOf12, n0.a);
        Integer valueOf13 = 25;
        int i26 = 0;
        c3.G = c3.a("measurement.upload.max_public_user_properties", valueOf13, valueOf13, i26);
        Integer valueOf16 = 500;
        c3.H = c3.a("measurement.upload.max_event_name_cardinality", valueOf16, valueOf16, i26);
        String str5 = "measurement.upload.max_public_event_params";
        c3.I = c3.a(str5, valueOf13, valueOf13, i26);
        Long valueOf14 = Long.valueOf(5000);
        c3.J = c3.a("measurement.service_client.idle_disconnect_millis", valueOf14, valueOf14, o0.a);
        Boolean fALSE = Boolean.FALSE;
        c3.K = c3.a("measurement.test.boolean_flag", fALSE, fALSE, p0.a);
        String str76 = "---";
        c3.L = c3.a("measurement.test.string_flag", str76, str76, q0.a);
        Long valueOf17 = Long.valueOf(-1);
        c3.M = c3.a("measurement.test.long_flag", valueOf17, valueOf17, r0.a);
        Integer valueOf18 = -2;
        String str78 = "measurement.test.int_flag";
        c3.N = c3.a(str78, valueOf18, valueOf18, s0.a);
        Double valueOf19 = Double.valueOf(-4609434218613702656L);
        c3.O = c3.a("measurement.test.double_flag", valueOf19, valueOf19, u0.a);
        Integer valueOf20 = 50;
        c3.P = c3.a("measurement.experiment.max_ids", valueOf20, valueOf20, v0.a);
        c3.Q = c3.a("measurement.max_bundles_per_iteration", valueOf22, valueOf22, w0.a);
        c3.R = c3.a("measurement.sdk.attribution.cache.ttl", valueOf5, valueOf5, x0.a);
        c3.S = c3.a("measurement.validation.internal_limits_internal_event_params", fALSE, fALSE, z0.a);
        Boolean tRUE = Boolean.TRUE;
        c3.T = c3.a("measurement.collection.firebase_global_collection_flag_enabled", tRUE, tRUE, a1.a);
        c3.U = c3.a("measurement.collection.redundant_engagement_removal_enabled", fALSE, fALSE, b1.a);
        c3.V = c3.a("measurement.collection.log_event_and_bundle_v2", tRUE, tRUE, d1.a);
        c3.W = c3.a("measurement.quality.checksum", fALSE, fALSE, i26);
        c3.X = c3.a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", fALSE, fALSE, e1.a);
        c3.Y = c3.a("measurement.audience.refresh_event_count_filters_timestamp", fALSE, fALSE, g1.a);
        c3.Z = c3.a("measurement.audience.use_bundle_timestamp_for_event_count_filters", fALSE, fALSE, h1.a);
        c3.a0 = c3.a("measurement.sdk.collection.retrieve_deeplink_from_bow_2", tRUE, tRUE, i1.a);
        c3.b0 = c3.a("measurement.sdk.collection.last_deep_link_referrer_campaign2", fALSE, fALSE, j1.a);
        c3.c0 = c3.a("measurement.sdk.collection.enable_extend_user_property_size", tRUE, tRUE, k1.a);
        c3.d0 = c3.a("measurement.ga.ga_app_id", fALSE, fALSE, m1.a);
        c3.e0 = c3.a("measurement.lifecycle.app_in_background_parameter", fALSE, fALSE, n1.a);
        c3.f0 = c3.a("measurement.integration.disable_firebase_instance_id", fALSE, fALSE, o1.a);
        c3.g0 = c3.a("measurement.lifecycle.app_backgrounded_engagement", fALSE, fALSE, p1.a);
        c3.h0 = c3.a("measurement.collection.service.update_with_analytics_fix", fALSE, fALSE, r1.a);
        c3.i0 = c3.a("measurement.client.firebase_feature_rollout.v1.enable", tRUE, tRUE, s1.a);
        c3.j0 = c3.a("measurement.client.sessions.check_on_reset_and_enable2", tRUE, tRUE, t1.a);
        c3.k0 = c3.a("measurement.scheduler.task_thread.cleanup_on_exit", fALSE, fALSE, u1.a);
        c3.l0 = c3.a("measurement.upload.file_truncate_fix", fALSE, fALSE, v1.a);
        c3.a("measurement.collection.synthetic_data_mitigation", fALSE, fALSE, w1.a);
        c3.m0 = c3.a("measurement.androidId.delete_feature", tRUE, tRUE, y1.a);
        Integer valueOf21 = 203600;
        c3.n0 = c3.a("measurement.service.storage_consent_support_version", valueOf21, valueOf21, z1.a);
        c3.a("measurement.client.click_identifier_control.dev", fALSE, fALSE, a2.a);
        c3.a("measurement.service.click_identifier_control", fALSE, fALSE, c2.a);
        c3.o0 = c3.a("measurement.config.persist_last_modified", tRUE, tRUE, e2.a);
        c3.p0 = c3.a("measurement.client.consent.suppress_1p_in_ga4f_install", tRUE, tRUE, f2.a);
        c3.q0 = c3.a("measurement.client.consent.gmpappid_worker_thread_fix", tRUE, tRUE, g2.a);
        c3.r0 = c3.a("measurement.module.pixie.ees", tRUE, tRUE, h2.a);
        c3.s0 = c3.a("measurement.module.pixie.fix_array", tRUE, tRUE, i2.a);
        c3.t0 = c3.a("measurement.adid_zero.service", fALSE, fALSE, j2.a);
        c3.u0 = c3.a("measurement.adid_zero.remove_lair_if_adidzero_false", tRUE, tRUE, l2.a);
        c3.v0 = c3.a("measurement.adid_zero.remove_lair_if_userid_cleared", tRUE, tRUE, m2.a);
        c3.a("measurement.adid_zero.adid_uid", fALSE, fALSE, o2.a);
        c3.w0 = c3.a("measurement.adid_zero.app_instance_id_fix", tRUE, tRUE, p2.a);
        c3.x0 = c3.a("measurement.service.refactor.package_side_screen", tRUE, tRUE, q2.a);
        c3.y0 = c3.a("measurement.config.fix_feature_flags_from_config", tRUE, tRUE, r2.a);
        c3.z0 = c3.a("measurement.service.event_config_fix", tRUE, tRUE, s2.a);
    }

    static <V> com.google.android.gms.measurement.internal.b3<V> a(String string, V v2, V v3, com.google.android.gms.measurement.internal.y2<V> y24) {
        super(string, v2, v3, y24, 0);
        c3.a.add(b3Var2);
        return b3Var2;
    }

    static List b() {
        return c3.a;
    }

    public static Map<String, String> c(Context context) {
        Map obj1;
        obj1 = c6.b(context.getContentResolver(), m6.a("com.google.android.gms.measurement"));
        if (obj1 == null) {
            obj1 = Collections.emptyMap();
        } else {
            obj1 = obj1.c();
        }
        return obj1;
    }
}
